import { NotificationCategory, NotificationSeverity } from '@prisma/client';

export type NotificationEventType =
  | 'NEW_ADMISSION'
  | 'STUDENT_CREATED'
  | 'STUDENT_UPDATED'
  | 'STUDENT_DELETED'
  | 'FEE_INVOICE_GENERATED'
  | 'FEE_DUE_REMINDER'
  | 'FEE_PAID'
  | 'PAYROLL_GENERATED'
  | 'PAYROLL_PAID'
  | 'ATTENDANCE_ABSENT'
  | 'ATTENDANCE_SUBMITTED'
  | 'EXAM_SCHEDULED'
  | 'EXAM_CREATED'
  | 'EXAM_RESULT_PUBLISHED'
  | 'LIBRARY_BOOK_ISSUED'
  | 'LIBRARY_BOOK_RETURNED'
  | 'TRANSPORT_ASSIGNMENT_CHANGED'
  | 'SCHOOL_ACTIVATED'
  | 'SCHOOL_SUSPENDED'
  | 'PLAN_CHANGED'
  | 'PASSWORD_RESET'
  | 'NEW_STAFF'
  | 'NEW_TEACHER'
  | 'NEW_PARENT'
  | 'NEW_USER'
  | 'DOCUMENT_UPLOADED'
  | 'DOCUMENT_DELETED'
  | 'SALARY_PROCESSED'
  | 'NEW_ANNOUNCEMENT'
  | 'HOMEWORK_ASSIGNED'
  | 'HOMEWORK_DUE_TOMORROW'
  | 'HOMEWORK_OVERDUE'
  | 'HOMEWORK_GRADED'
  | 'ONLINE_CLASS_SCHEDULED'
  | 'ONLINE_CLASS_REMINDER'
  | 'ONLINE_CLASS_STARTED'
  | 'ONLINE_CLASS_CANCELLED'
  | 'ONLINE_CLASS_UPDATED'
  | 'CALENDAR_EVENT_PUBLISHED'
  | 'CALENDAR_EVENT_UPDATED'
  | 'CALENDAR_EVENT_CANCELLED'
  | 'CALENDAR_EVENT_REMINDER'
  | 'TIMETABLE_CHANGED'
  | 'HOLIDAY_ANNOUNCEMENT'
  | 'EMERGENCY_NOTICE'
  | 'BIRTHDAY_GREETING'
  | 'GENERAL_ANNOUNCEMENT';

export interface SchoolNotificationSettings {
  emailEnabled: boolean;
  smsEnabled: boolean;
  whatsappEnabled: boolean;
}

export interface NotificationPayload {
  recipient: string;
  subject?: string;
  body: string;
  channel: 'IN_APP' | 'EMAIL' | 'SMS' | 'WHATSAPP' | 'PUSH';
  schoolId?: string;
  eventType?: NotificationEventType;
  userId?: string;
  senderId?: string;
  campaignId?: string;
  templateId?: string;
  deviceToken?: string;
  /** When retrying, update existing log instead of creating a new one */
  skipLogCreate?: boolean;
  existingLogId?: string;
}

export interface InAppNotificationPayload {
  userId: string;
  schoolId?: string;
  eventType: NotificationEventType;
  title: string;
  body: string;
  linkUrl?: string;
  type?: NotificationSeverity;
  category?: NotificationCategory;
  dedupeKey?: string;
}

export const EVENT_CATEGORY_MAP: Partial<Record<NotificationEventType, NotificationCategory>> = {
  NEW_ADMISSION: 'STUDENT',
  STUDENT_CREATED: 'STUDENT',
  STUDENT_UPDATED: 'STUDENT',
  STUDENT_DELETED: 'STUDENT',
  FEE_INVOICE_GENERATED: 'FEE',
  FEE_DUE_REMINDER: 'FEE',
  FEE_PAID: 'FEE',
  PAYROLL_GENERATED: 'PAYROLL',
  PAYROLL_PAID: 'PAYROLL',
  SALARY_PROCESSED: 'PAYROLL',
  ATTENDANCE_ABSENT: 'ATTENDANCE',
  ATTENDANCE_SUBMITTED: 'ATTENDANCE',
  EXAM_SCHEDULED: 'EXAM',
  EXAM_CREATED: 'EXAM',
  EXAM_RESULT_PUBLISHED: 'EXAM',
  LIBRARY_BOOK_ISSUED: 'LIBRARY',
  LIBRARY_BOOK_RETURNED: 'LIBRARY',
  TRANSPORT_ASSIGNMENT_CHANGED: 'TRANSPORT',
  SCHOOL_ACTIVATED: 'SYSTEM',
  SCHOOL_SUSPENDED: 'SYSTEM',
  PLAN_CHANGED: 'SYSTEM',
  PASSWORD_RESET: 'SYSTEM',
  NEW_STAFF: 'SYSTEM',
  NEW_TEACHER: 'SYSTEM',
  NEW_PARENT: 'STUDENT',
  NEW_USER: 'SYSTEM',
  DOCUMENT_UPLOADED: 'STUDENT',
  DOCUMENT_DELETED: 'STUDENT',
  NEW_ANNOUNCEMENT: 'ANNOUNCEMENT',
  HOMEWORK_ASSIGNED: 'HOMEWORK',
  HOMEWORK_DUE_TOMORROW: 'HOMEWORK',
  HOMEWORK_OVERDUE: 'HOMEWORK',
  HOMEWORK_GRADED: 'HOMEWORK',
  ONLINE_CLASS_SCHEDULED: 'ONLINE_CLASS',
  ONLINE_CLASS_REMINDER: 'ONLINE_CLASS',
  ONLINE_CLASS_STARTED: 'ONLINE_CLASS',
  ONLINE_CLASS_CANCELLED: 'ONLINE_CLASS',
  ONLINE_CLASS_UPDATED: 'ONLINE_CLASS',
  CALENDAR_EVENT_PUBLISHED: 'CALENDAR',
  CALENDAR_EVENT_UPDATED: 'CALENDAR',
  CALENDAR_EVENT_CANCELLED: 'CALENDAR',
  CALENDAR_EVENT_REMINDER: 'CALENDAR',
  TIMETABLE_CHANGED: 'TIMETABLE',
  HOLIDAY_ANNOUNCEMENT: 'HOLIDAY',
  EMERGENCY_NOTICE: 'EMERGENCY',
  BIRTHDAY_GREETING: 'BIRTHDAY',
  GENERAL_ANNOUNCEMENT: 'ANNOUNCEMENT',
};

export const EVENT_SEVERITY_MAP: Partial<Record<NotificationEventType, NotificationSeverity>> = {
  STUDENT_DELETED: 'WARNING',
  FEE_DUE_REMINDER: 'WARNING',
  ATTENDANCE_ABSENT: 'WARNING',
  SCHOOL_SUSPENDED: 'ERROR',
  DOCUMENT_DELETED: 'WARNING',
  FEE_PAID: 'SUCCESS',
  PAYROLL_PAID: 'SUCCESS',
  EXAM_RESULT_PUBLISHED: 'SUCCESS',
  STUDENT_CREATED: 'SUCCESS',
  NEW_ADMISSION: 'SUCCESS',
  LIBRARY_BOOK_RETURNED: 'SUCCESS',
  SCHOOL_ACTIVATED: 'SUCCESS',
  HOMEWORK_DUE_TOMORROW: 'WARNING',
  HOMEWORK_OVERDUE: 'ERROR',
  HOMEWORK_GRADED: 'SUCCESS',
  ONLINE_CLASS_REMINDER: 'WARNING',
  ONLINE_CLASS_STARTED: 'SUCCESS',
  ONLINE_CLASS_CANCELLED: 'WARNING',
  EMERGENCY_NOTICE: 'ERROR',
  BIRTHDAY_GREETING: 'SUCCESS',
  CALENDAR_EVENT_PUBLISHED: 'SUCCESS',
  CALENDAR_EVENT_CANCELLED: 'WARNING',
  CALENDAR_EVENT_REMINDER: 'WARNING',
};
