/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyOtpRouteImport } from './routes/verify-otp'
import { Route as UsersRouteImport } from './routes/users'
import { Route as TransportRouteImport } from './routes/transport'
import { Route as TimetableRouteImport } from './routes/timetable'
import { Route as TeachersRouteImport } from './routes/teachers'
import { Route as TeacherRouteImport } from './routes/teacher'
import { Route as SuperAdminRouteImport } from './routes/super-admin'
import { Route as SubjectsRouteImport } from './routes/subjects'
import { Route as StudentsRouteImport } from './routes/students'
import { Route as StudentRouteImport } from './routes/student'
import { Route as StaffRouteImport } from './routes/staff'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RolesRouteImport } from './routes/roles'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as PayrollRouteImport } from './routes/payroll'
import { Route as ParentsRouteImport } from './routes/parents'
import { Route as ParentRouteImport } from './routes/parent'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as FeesRouteImport } from './routes/fees'
import { Route as ExpensesRouteImport } from './routes/expenses'
import { Route as ExamsRouteImport } from './routes/exams'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CommunicationRouteImport } from './routes/communication'
import { Route as ClassesRouteImport } from './routes/classes'
import { Route as AttendanceRouteImport } from './routes/attendance'
import { Route as AcademicCalendarRouteImport } from './routes/academic-calendar'
import { Route as IndexRouteImport } from './routes/index'

const VerifyOtpRoute = VerifyOtpRouteImport.update({
  id: '/verify-otp',
  path: '/verify-otp',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const TransportRoute = TransportRouteImport.update({
  id: '/transport',
  path: '/transport',
  getParentRoute: () => rootRouteImport,
} as any)
const TimetableRoute = TimetableRouteImport.update({
  id: '/timetable',
  path: '/timetable',
  getParentRoute: () => rootRouteImport,
} as any)
const TeachersRoute = TeachersRouteImport.update({
  id: '/teachers',
  path: '/teachers',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherRoute = TeacherRouteImport.update({
  id: '/teacher',
  path: '/teacher',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminRoute = SuperAdminRouteImport.update({
  id: '/super-admin',
  path: '/super-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const SubjectsRoute = SubjectsRouteImport.update({
  id: '/subjects',
  path: '/subjects',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentsRoute = StudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentRoute = StudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRoute = StaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RolesRoute = RolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const PayrollRoute = PayrollRouteImport.update({
  id: '/payroll',
  path: '/payroll',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentsRoute = ParentsRouteImport.update({
  id: '/parents',
  path: '/parents',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentRoute = ParentRouteImport.update({
  id: '/parent',
  path: '/parent',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const FeesRoute = FeesRouteImport.update({
  id: '/fees',
  path: '/fees',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpensesRoute = ExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamsRoute = ExamsRouteImport.update({
  id: '/exams',
  path: '/exams',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunicationRoute = CommunicationRouteImport.update({
  id: '/communication',
  path: '/communication',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassesRoute = ClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => rootRouteImport,
} as any)
const AttendanceRoute = AttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademicCalendarRoute = AcademicCalendarRouteImport.update({
  id: '/academic-calendar',
  path: '/academic-calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/academic-calendar': typeof AcademicCalendarRoute
  '/attendance': typeof AttendanceRoute
  '/classes': typeof ClassesRoute
  '/communication': typeof CommunicationRoute
  '/dashboard': typeof DashboardRoute
  '/exams': typeof ExamsRoute
  '/expenses': typeof ExpensesRoute
  '/fees': typeof FeesRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/parent': typeof ParentRoute
  '/parents': typeof ParentsRoute
  '/payroll': typeof PayrollRoute
  '/reports': typeof ReportsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/roles': typeof RolesRoute
  '/settings': typeof SettingsRoute
  '/staff': typeof StaffRoute
  '/student': typeof StudentRoute
  '/students': typeof StudentsRoute
  '/subjects': typeof SubjectsRoute
  '/super-admin': typeof SuperAdminRoute
  '/teacher': typeof TeacherRoute
  '/teachers': typeof TeachersRoute
  '/timetable': typeof TimetableRoute
  '/transport': typeof TransportRoute
  '/users': typeof UsersRoute
  '/verify-otp': typeof VerifyOtpRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/academic-calendar': typeof AcademicCalendarRoute
  '/attendance': typeof AttendanceRoute
  '/classes': typeof ClassesRoute
  '/communication': typeof CommunicationRoute
  '/dashboard': typeof DashboardRoute
  '/exams': typeof ExamsRoute
  '/expenses': typeof ExpensesRoute
  '/fees': typeof FeesRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/parent': typeof ParentRoute
  '/parents': typeof ParentsRoute
  '/payroll': typeof PayrollRoute
  '/reports': typeof ReportsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/roles': typeof RolesRoute
  '/settings': typeof SettingsRoute
  '/staff': typeof StaffRoute
  '/student': typeof StudentRoute
  '/students': typeof StudentsRoute
  '/subjects': typeof SubjectsRoute
  '/super-admin': typeof SuperAdminRoute
  '/teacher': typeof TeacherRoute
  '/teachers': typeof TeachersRoute
  '/timetable': typeof TimetableRoute
  '/transport': typeof TransportRoute
  '/users': typeof UsersRoute
  '/verify-otp': typeof VerifyOtpRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/academic-calendar': typeof AcademicCalendarRoute
  '/attendance': typeof AttendanceRoute
  '/classes': typeof ClassesRoute
  '/communication': typeof CommunicationRoute
  '/dashboard': typeof DashboardRoute
  '/exams': typeof ExamsRoute
  '/expenses': typeof ExpensesRoute
  '/fees': typeof FeesRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/parent': typeof ParentRoute
  '/parents': typeof ParentsRoute
  '/payroll': typeof PayrollRoute
  '/reports': typeof ReportsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/roles': typeof RolesRoute
  '/settings': typeof SettingsRoute
  '/staff': typeof StaffRoute
  '/student': typeof StudentRoute
  '/students': typeof StudentsRoute
  '/subjects': typeof SubjectsRoute
  '/super-admin': typeof SuperAdminRoute
  '/teacher': typeof TeacherRoute
  '/teachers': typeof TeachersRoute
  '/timetable': typeof TimetableRoute
  '/transport': typeof TransportRoute
  '/users': typeof UsersRoute
  '/verify-otp': typeof VerifyOtpRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/academic-calendar'
    | '/attendance'
    | '/classes'
    | '/communication'
    | '/dashboard'
    | '/exams'
    | '/expenses'
    | '/fees'
    | '/library'
    | '/login'
    | '/notifications'
    | '/parent'
    | '/parents'
    | '/payroll'
    | '/reports'
    | '/reset-password'
    | '/roles'
    | '/settings'
    | '/staff'
    | '/student'
    | '/students'
    | '/subjects'
    | '/super-admin'
    | '/teacher'
    | '/teachers'
    | '/timetable'
    | '/transport'
    | '/users'
    | '/verify-otp'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/academic-calendar'
    | '/attendance'
    | '/classes'
    | '/communication'
    | '/dashboard'
    | '/exams'
    | '/expenses'
    | '/fees'
    | '/library'
    | '/login'
    | '/notifications'
    | '/parent'
    | '/parents'
    | '/payroll'
    | '/reports'
    | '/reset-password'
    | '/roles'
    | '/settings'
    | '/staff'
    | '/student'
    | '/students'
    | '/subjects'
    | '/super-admin'
    | '/teacher'
    | '/teachers'
    | '/timetable'
    | '/transport'
    | '/users'
    | '/verify-otp'
  id:
    | '__root__'
    | '/'
    | '/academic-calendar'
    | '/attendance'
    | '/classes'
    | '/communication'
    | '/dashboard'
    | '/exams'
    | '/expenses'
    | '/fees'
    | '/library'
    | '/login'
    | '/notifications'
    | '/parent'
    | '/parents'
    | '/payroll'
    | '/reports'
    | '/reset-password'
    | '/roles'
    | '/settings'
    | '/staff'
    | '/student'
    | '/students'
    | '/subjects'
    | '/super-admin'
    | '/teacher'
    | '/teachers'
    | '/timetable'
    | '/transport'
    | '/users'
    | '/verify-otp'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcademicCalendarRoute: typeof AcademicCalendarRoute
  AttendanceRoute: typeof AttendanceRoute
  ClassesRoute: typeof ClassesRoute
  CommunicationRoute: typeof CommunicationRoute
  DashboardRoute: typeof DashboardRoute
  ExamsRoute: typeof ExamsRoute
  ExpensesRoute: typeof ExpensesRoute
  FeesRoute: typeof FeesRoute
  LibraryRoute: typeof LibraryRoute
  LoginRoute: typeof LoginRoute
  NotificationsRoute: typeof NotificationsRoute
  ParentRoute: typeof ParentRoute
  ParentsRoute: typeof ParentsRoute
  PayrollRoute: typeof PayrollRoute
  ReportsRoute: typeof ReportsRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  RolesRoute: typeof RolesRoute
  SettingsRoute: typeof SettingsRoute
  StaffRoute: typeof StaffRoute
  StudentRoute: typeof StudentRoute
  StudentsRoute: typeof StudentsRoute
  SubjectsRoute: typeof SubjectsRoute
  SuperAdminRoute: typeof SuperAdminRoute
  TeacherRoute: typeof TeacherRoute
  TeachersRoute: typeof TeachersRoute
  TimetableRoute: typeof TimetableRoute
  TransportRoute: typeof TransportRoute
  UsersRoute: typeof UsersRoute
  VerifyOtpRoute: typeof VerifyOtpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-otp': {
      id: '/verify-otp'
      path: '/verify-otp'
      fullPath: '/verify-otp'
      preLoaderRoute: typeof VerifyOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transport': {
      id: '/transport'
      path: '/transport'
      fullPath: '/transport'
      preLoaderRoute: typeof TransportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timetable': {
      id: '/timetable'
      path: '/timetable'
      fullPath: '/timetable'
      preLoaderRoute: typeof TimetableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teachers': {
      id: '/teachers'
      path: '/teachers'
      fullPath: '/teachers'
      preLoaderRoute: typeof TeachersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher': {
      id: '/teacher'
      path: '/teacher'
      fullPath: '/teacher'
      preLoaderRoute: typeof TeacherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin': {
      id: '/super-admin'
      path: '/super-admin'
      fullPath: '/super-admin'
      preLoaderRoute: typeof SuperAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subjects': {
      id: '/subjects'
      path: '/subjects'
      fullPath: '/subjects'
      preLoaderRoute: typeof SubjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/students': {
      id: '/students'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof StudentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roles': {
      id: '/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof RolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payroll': {
      id: '/payroll'
      path: '/payroll'
      fullPath: '/payroll'
      preLoaderRoute: typeof PayrollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parents': {
      id: '/parents'
      path: '/parents'
      fullPath: '/parents'
      preLoaderRoute: typeof ParentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parent': {
      id: '/parent'
      path: '/parent'
      fullPath: '/parent'
      preLoaderRoute: typeof ParentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fees': {
      id: '/fees'
      path: '/fees'
      fullPath: '/fees'
      preLoaderRoute: typeof FeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expenses': {
      id: '/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof ExpensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exams': {
      id: '/exams'
      path: '/exams'
      fullPath: '/exams'
      preLoaderRoute: typeof ExamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/communication': {
      id: '/communication'
      path: '/communication'
      fullPath: '/communication'
      preLoaderRoute: typeof CommunicationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classes': {
      id: '/classes'
      path: '/classes'
      fullPath: '/classes'
      preLoaderRoute: typeof ClassesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attendance': {
      id: '/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academic-calendar': {
      id: '/academic-calendar'
      path: '/academic-calendar'
      fullPath: '/academic-calendar'
      preLoaderRoute: typeof AcademicCalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcademicCalendarRoute: AcademicCalendarRoute,
  AttendanceRoute: AttendanceRoute,
  ClassesRoute: ClassesRoute,
  CommunicationRoute: CommunicationRoute,
  DashboardRoute: DashboardRoute,
  ExamsRoute: ExamsRoute,
  ExpensesRoute: ExpensesRoute,
  FeesRoute: FeesRoute,
  LibraryRoute: LibraryRoute,
  LoginRoute: LoginRoute,
  NotificationsRoute: NotificationsRoute,
  ParentRoute: ParentRoute,
  ParentsRoute: ParentsRoute,
  PayrollRoute: PayrollRoute,
  ReportsRoute: ReportsRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  RolesRoute: RolesRoute,
  SettingsRoute: SettingsRoute,
  StaffRoute: StaffRoute,
  StudentRoute: StudentRoute,
  StudentsRoute: StudentsRoute,
  SubjectsRoute: SubjectsRoute,
  SuperAdminRoute: SuperAdminRoute,
  TeacherRoute: TeacherRoute,
  TeachersRoute: TeachersRoute,
  TimetableRoute: TimetableRoute,
  TransportRoute: TransportRoute,
  UsersRoute: UsersRoute,
  VerifyOtpRoute: VerifyOtpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
