-- Align Prisma schema with the older partial migrations.
-- Safe for a fresh Render database (runs after init/fee/attendance/exam).
-- Uses IF NOT EXISTS / duplicate_object guards for databases that already used db push.

DO $$ BEGIN
  CREATE TYPE "UserRole" AS ENUM ('SUPER_ADMIN', 'PLATFORM_MANAGER', 'SCHOOL_ADMIN', 'ACCOUNTANT', 'TEACHER', 'RECEPTIONIST', 'PARENT', 'STUDENT');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;
  ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'SUPER_ADMIN';
  ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'PLATFORM_MANAGER';
  ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'SCHOOL_ADMIN';
  ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'ACCOUNTANT';
  ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'TEACHER';
  ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'RECEPTIONIST';
  ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'PARENT';
  ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'STUDENT';

DO $$ BEGIN
  CREATE TYPE "UserStatus" AS ENUM ('ACTIVE', 'INACTIVE');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;
  ALTER TYPE "UserStatus" ADD VALUE IF NOT EXISTS 'ACTIVE';
  ALTER TYPE "UserStatus" ADD VALUE IF NOT EXISTS 'INACTIVE';

DO $$ BEGIN
  CREATE TYPE "SchoolStatus" AS ENUM ('ACTIVE', 'INACTIVE', 'SUSPENDED');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;
  ALTER TYPE "SchoolStatus" ADD VALUE IF NOT EXISTS 'ACTIVE';
  ALTER TYPE "SchoolStatus" ADD VALUE IF NOT EXISTS 'INACTIVE';
  ALTER TYPE "SchoolStatus" ADD VALUE IF NOT EXISTS 'SUSPENDED';

DO $$ BEGIN
  CREATE TYPE "FeeInvoiceStatus" AS ENUM ('UNPAID', 'PARTIAL', 'PAID', 'CANCELLED');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;
  ALTER TYPE "FeeInvoiceStatus" ADD VALUE IF NOT EXISTS 'UNPAID';
  ALTER TYPE "FeeInvoiceStatus" ADD VALUE IF NOT EXISTS 'PARTIAL';
  ALTER TYPE "FeeInvoiceStatus" ADD VALUE IF NOT EXISTS 'PAID';
  ALTER TYPE "FeeInvoiceStatus" ADD VALUE IF NOT EXISTS 'CANCELLED';

DO $$ BEGIN
  CREATE TYPE "AttendanceStatus" AS ENUM ('PRESENT', 'ABSENT', 'LEAVE', 'LATE');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;
  ALTER TYPE "AttendanceStatus" ADD VALUE IF NOT EXISTS 'PRESENT';
  ALTER TYPE "AttendanceStatus" ADD VALUE IF NOT EXISTS 'ABSENT';
  ALTER TYPE "AttendanceStatus" ADD VALUE IF NOT EXISTS 'LEAVE';
  ALTER TYPE "AttendanceStatus" ADD VALUE IF NOT EXISTS 'LATE';

DO $$ BEGIN
  CREATE TYPE "ExamStatus" AS ENUM ('DRAFT', 'ACTIVE', 'COMPLETED', 'CANCELLED');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;
  ALTER TYPE "ExamStatus" ADD VALUE IF NOT EXISTS 'DRAFT';
  ALTER TYPE "ExamStatus" ADD VALUE IF NOT EXISTS 'ACTIVE';
  ALTER TYPE "ExamStatus" ADD VALUE IF NOT EXISTS 'COMPLETED';
  ALTER TYPE "ExamStatus" ADD VALUE IF NOT EXISTS 'CANCELLED';

DO $$ BEGIN
  CREATE TYPE "PayrollStatus" AS ENUM ('PENDING', 'PAID', 'CANCELLED');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;
  ALTER TYPE "PayrollStatus" ADD VALUE IF NOT EXISTS 'PENDING';
  ALTER TYPE "PayrollStatus" ADD VALUE IF NOT EXISTS 'PAID';
  ALTER TYPE "PayrollStatus" ADD VALUE IF NOT EXISTS 'CANCELLED';

DO $$ BEGIN
  CREATE TYPE "StaffType" AS ENUM ('TEACHER', 'STAFF');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;
  ALTER TYPE "StaffType" ADD VALUE IF NOT EXISTS 'TEACHER';
  ALTER TYPE "StaffType" ADD VALUE IF NOT EXISTS 'STAFF';

DO $$ BEGIN
  CREATE TYPE "PlanTier" AS ENUM ('TRIAL', 'BASIC', 'PROFESSIONAL', 'ENTERPRISE');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;
  ALTER TYPE "PlanTier" ADD VALUE IF NOT EXISTS 'TRIAL';
  ALTER TYPE "PlanTier" ADD VALUE IF NOT EXISTS 'BASIC';
  ALTER TYPE "PlanTier" ADD VALUE IF NOT EXISTS 'PROFESSIONAL';
  ALTER TYPE "PlanTier" ADD VALUE IF NOT EXISTS 'ENTERPRISE';

DO $$ BEGIN
  CREATE TYPE "SubscriptionStatus" AS ENUM ('TRIAL', 'ACTIVE', 'EXPIRED', 'SUSPENDED', 'CANCELLED');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;
  ALTER TYPE "SubscriptionStatus" ADD VALUE IF NOT EXISTS 'TRIAL';
  ALTER TYPE "SubscriptionStatus" ADD VALUE IF NOT EXISTS 'ACTIVE';
  ALTER TYPE "SubscriptionStatus" ADD VALUE IF NOT EXISTS 'EXPIRED';
  ALTER TYPE "SubscriptionStatus" ADD VALUE IF NOT EXISTS 'SUSPENDED';
  ALTER TYPE "SubscriptionStatus" ADD VALUE IF NOT EXISTS 'CANCELLED';

DO $$ BEGIN
  CREATE TYPE "SaasInvoiceStatus" AS ENUM ('PENDING', 'PAID', 'FAILED', 'CANCELLED');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;
  ALTER TYPE "SaasInvoiceStatus" ADD VALUE IF NOT EXISTS 'PENDING';
  ALTER TYPE "SaasInvoiceStatus" ADD VALUE IF NOT EXISTS 'PAID';
  ALTER TYPE "SaasInvoiceStatus" ADD VALUE IF NOT EXISTS 'FAILED';
  ALTER TYPE "SaasInvoiceStatus" ADD VALUE IF NOT EXISTS 'CANCELLED';

DO $$ BEGIN
  CREATE TYPE "AuditAction" AS ENUM ('SCHOOL_CREATED', 'SCHOOL_UPDATED', 'SCHOOL_ACTIVATED', 'SCHOOL_SUSPENDED', 'SCHOOL_DELETED', 'PLAN_ASSIGNED', 'PLAN_CHANGED', 'SUBSCRIPTION_EXTENDED', 'IMPERSONATION', 'SETTING_UPDATED', 'USER_CREATED', 'USER_UPDATED', 'USER_DELETED', 'USER_ACTIVATED', 'USER_DEACTIVATED', 'USER_LOCKED', 'USER_UNLOCKED', 'PASSWORD_RESET', 'ROLE_CHANGED', 'SCHOOL_ADMIN_CHANGED', 'NOTIFICATION_SENT', 'NOTIFICATION_SCHEDULED', 'NOTIFICATION_TEMPLATE_UPDATED', 'LOGIN_OTP_GENERATED', 'LOGIN_OTP_SENT', 'LOGIN_OTP_VERIFY_SUCCESS', 'LOGIN_OTP_VERIFY_FAILURE', 'LOGIN_OTP_EXPIRED', 'LOGIN_OTP_RESEND');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;
  ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'SCHOOL_CREATED';
  ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'SCHOOL_UPDATED';
  ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'SCHOOL_ACTIVATED';
  ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'SCHOOL_SUSPENDED';
  ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'SCHOOL_DELETED';
  ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'PLAN_ASSIGNED';
  ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'PLAN_CHANGED';
  ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'SUBSCRIPTION_EXTENDED';
  ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'IMPERSONATION';
  ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'SETTING_UPDATED';
  ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'USER_CREATED';
  ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'USER_UPDATED';
  ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'USER_DELETED';
  ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'USER_ACTIVATED';
  ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'USER_DEACTIVATED';
  ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'USER_LOCKED';
  ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'USER_UNLOCKED';
  ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'PASSWORD_RESET';
  ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'ROLE_CHANGED';
  ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'SCHOOL_ADMIN_CHANGED';
  ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'NOTIFICATION_SENT';
  ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'NOTIFICATION_SCHEDULED';
  ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'NOTIFICATION_TEMPLATE_UPDATED';
  ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'LOGIN_OTP_GENERATED';
  ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'LOGIN_OTP_SENT';
  ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'LOGIN_OTP_VERIFY_SUCCESS';
  ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'LOGIN_OTP_VERIFY_FAILURE';
  ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'LOGIN_OTP_EXPIRED';
  ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'LOGIN_OTP_RESEND';

DO $$ BEGIN
  CREATE TYPE "DocumentType" AS ENUM ('BIRTH_CERTIFICATE', 'B_FORM', 'ID_CARD', 'TRANSFER_CERTIFICATE', 'PHOTO', 'SCHOOL_LOGO', 'OTHER');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;
  ALTER TYPE "DocumentType" ADD VALUE IF NOT EXISTS 'BIRTH_CERTIFICATE';
  ALTER TYPE "DocumentType" ADD VALUE IF NOT EXISTS 'B_FORM';
  ALTER TYPE "DocumentType" ADD VALUE IF NOT EXISTS 'ID_CARD';
  ALTER TYPE "DocumentType" ADD VALUE IF NOT EXISTS 'TRANSFER_CERTIFICATE';
  ALTER TYPE "DocumentType" ADD VALUE IF NOT EXISTS 'PHOTO';
  ALTER TYPE "DocumentType" ADD VALUE IF NOT EXISTS 'SCHOOL_LOGO';
  ALTER TYPE "DocumentType" ADD VALUE IF NOT EXISTS 'OTHER';

DO $$ BEGIN
  CREATE TYPE "NotificationChannel" AS ENUM ('IN_APP', 'EMAIL', 'SMS', 'WHATSAPP', 'PUSH');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;
  ALTER TYPE "NotificationChannel" ADD VALUE IF NOT EXISTS 'IN_APP';
  ALTER TYPE "NotificationChannel" ADD VALUE IF NOT EXISTS 'EMAIL';
  ALTER TYPE "NotificationChannel" ADD VALUE IF NOT EXISTS 'SMS';
  ALTER TYPE "NotificationChannel" ADD VALUE IF NOT EXISTS 'WHATSAPP';
  ALTER TYPE "NotificationChannel" ADD VALUE IF NOT EXISTS 'PUSH';

DO $$ BEGIN
  CREATE TYPE "NotificationStatus" AS ENUM ('PENDING', 'SENT', 'DELIVERED', 'FAILED', 'RETRYING');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;
  ALTER TYPE "NotificationStatus" ADD VALUE IF NOT EXISTS 'PENDING';
  ALTER TYPE "NotificationStatus" ADD VALUE IF NOT EXISTS 'SENT';
  ALTER TYPE "NotificationStatus" ADD VALUE IF NOT EXISTS 'DELIVERED';
  ALTER TYPE "NotificationStatus" ADD VALUE IF NOT EXISTS 'FAILED';
  ALTER TYPE "NotificationStatus" ADD VALUE IF NOT EXISTS 'RETRYING';

DO $$ BEGIN
  CREATE TYPE "NotificationSeverity" AS ENUM ('INFO', 'SUCCESS', 'WARNING', 'ERROR');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;
  ALTER TYPE "NotificationSeverity" ADD VALUE IF NOT EXISTS 'INFO';
  ALTER TYPE "NotificationSeverity" ADD VALUE IF NOT EXISTS 'SUCCESS';
  ALTER TYPE "NotificationSeverity" ADD VALUE IF NOT EXISTS 'WARNING';
  ALTER TYPE "NotificationSeverity" ADD VALUE IF NOT EXISTS 'ERROR';

DO $$ BEGIN
  CREATE TYPE "NotificationCategory" AS ENUM ('STUDENT', 'FEE', 'PAYROLL', 'ATTENDANCE', 'EXAM', 'LIBRARY', 'TRANSPORT', 'SYSTEM', 'ANNOUNCEMENT', 'HOMEWORK', 'TIMETABLE', 'HOLIDAY', 'EMERGENCY', 'BIRTHDAY', 'ONLINE_CLASS', 'CALENDAR');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;
  ALTER TYPE "NotificationCategory" ADD VALUE IF NOT EXISTS 'STUDENT';
  ALTER TYPE "NotificationCategory" ADD VALUE IF NOT EXISTS 'FEE';
  ALTER TYPE "NotificationCategory" ADD VALUE IF NOT EXISTS 'PAYROLL';
  ALTER TYPE "NotificationCategory" ADD VALUE IF NOT EXISTS 'ATTENDANCE';
  ALTER TYPE "NotificationCategory" ADD VALUE IF NOT EXISTS 'EXAM';
  ALTER TYPE "NotificationCategory" ADD VALUE IF NOT EXISTS 'LIBRARY';
  ALTER TYPE "NotificationCategory" ADD VALUE IF NOT EXISTS 'TRANSPORT';
  ALTER TYPE "NotificationCategory" ADD VALUE IF NOT EXISTS 'SYSTEM';
  ALTER TYPE "NotificationCategory" ADD VALUE IF NOT EXISTS 'ANNOUNCEMENT';
  ALTER TYPE "NotificationCategory" ADD VALUE IF NOT EXISTS 'HOMEWORK';
  ALTER TYPE "NotificationCategory" ADD VALUE IF NOT EXISTS 'TIMETABLE';
  ALTER TYPE "NotificationCategory" ADD VALUE IF NOT EXISTS 'HOLIDAY';
  ALTER TYPE "NotificationCategory" ADD VALUE IF NOT EXISTS 'EMERGENCY';
  ALTER TYPE "NotificationCategory" ADD VALUE IF NOT EXISTS 'BIRTHDAY';
  ALTER TYPE "NotificationCategory" ADD VALUE IF NOT EXISTS 'ONLINE_CLASS';
  ALTER TYPE "NotificationCategory" ADD VALUE IF NOT EXISTS 'CALENDAR';

DO $$ BEGIN
  CREATE TYPE "CampaignAudience" AS ENUM ('STUDENT', 'PARENT', 'TEACHER', 'STAFF', 'CLASS', 'SECTION', 'SCHOOL', 'SELECTED_USERS', 'MULTI_SCHOOL');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;
  ALTER TYPE "CampaignAudience" ADD VALUE IF NOT EXISTS 'STUDENT';
  ALTER TYPE "CampaignAudience" ADD VALUE IF NOT EXISTS 'PARENT';
  ALTER TYPE "CampaignAudience" ADD VALUE IF NOT EXISTS 'TEACHER';
  ALTER TYPE "CampaignAudience" ADD VALUE IF NOT EXISTS 'STAFF';
  ALTER TYPE "CampaignAudience" ADD VALUE IF NOT EXISTS 'CLASS';
  ALTER TYPE "CampaignAudience" ADD VALUE IF NOT EXISTS 'SECTION';
  ALTER TYPE "CampaignAudience" ADD VALUE IF NOT EXISTS 'SCHOOL';
  ALTER TYPE "CampaignAudience" ADD VALUE IF NOT EXISTS 'SELECTED_USERS';
  ALTER TYPE "CampaignAudience" ADD VALUE IF NOT EXISTS 'MULTI_SCHOOL';

DO $$ BEGIN
  CREATE TYPE "CampaignStatus" AS ENUM ('DRAFT', 'SCHEDULED', 'SENDING', 'SENT', 'PARTIAL', 'FAILED', 'CANCELLED');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;
  ALTER TYPE "CampaignStatus" ADD VALUE IF NOT EXISTS 'DRAFT';
  ALTER TYPE "CampaignStatus" ADD VALUE IF NOT EXISTS 'SCHEDULED';
  ALTER TYPE "CampaignStatus" ADD VALUE IF NOT EXISTS 'SENDING';
  ALTER TYPE "CampaignStatus" ADD VALUE IF NOT EXISTS 'SENT';
  ALTER TYPE "CampaignStatus" ADD VALUE IF NOT EXISTS 'PARTIAL';
  ALTER TYPE "CampaignStatus" ADD VALUE IF NOT EXISTS 'FAILED';
  ALTER TYPE "CampaignStatus" ADD VALUE IF NOT EXISTS 'CANCELLED';

DO $$ BEGIN
  CREATE TYPE "RecurrenceType" AS ENUM ('NONE', 'DAILY', 'WEEKLY', 'MONTHLY');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;
  ALTER TYPE "RecurrenceType" ADD VALUE IF NOT EXISTS 'NONE';
  ALTER TYPE "RecurrenceType" ADD VALUE IF NOT EXISTS 'DAILY';
  ALTER TYPE "RecurrenceType" ADD VALUE IF NOT EXISTS 'WEEKLY';
  ALTER TYPE "RecurrenceType" ADD VALUE IF NOT EXISTS 'MONTHLY';

DO $$ BEGIN
  CREATE TYPE "PushPlatform" AS ENUM ('WEB', 'ANDROID', 'IOS');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;
  ALTER TYPE "PushPlatform" ADD VALUE IF NOT EXISTS 'WEB';
  ALTER TYPE "PushPlatform" ADD VALUE IF NOT EXISTS 'ANDROID';
  ALTER TYPE "PushPlatform" ADD VALUE IF NOT EXISTS 'IOS';

DO $$ BEGIN
  CREATE TYPE "HomeworkPriority" AS ENUM ('LOW', 'MEDIUM', 'HIGH', 'URGENT');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;
  ALTER TYPE "HomeworkPriority" ADD VALUE IF NOT EXISTS 'LOW';
  ALTER TYPE "HomeworkPriority" ADD VALUE IF NOT EXISTS 'MEDIUM';
  ALTER TYPE "HomeworkPriority" ADD VALUE IF NOT EXISTS 'HIGH';
  ALTER TYPE "HomeworkPriority" ADD VALUE IF NOT EXISTS 'URGENT';

DO $$ BEGIN
  CREATE TYPE "HomeworkStatus" AS ENUM ('DRAFT', 'PUBLISHED', 'CLOSED', 'ARCHIVED');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;
  ALTER TYPE "HomeworkStatus" ADD VALUE IF NOT EXISTS 'DRAFT';
  ALTER TYPE "HomeworkStatus" ADD VALUE IF NOT EXISTS 'PUBLISHED';
  ALTER TYPE "HomeworkStatus" ADD VALUE IF NOT EXISTS 'CLOSED';
  ALTER TYPE "HomeworkStatus" ADD VALUE IF NOT EXISTS 'ARCHIVED';

DO $$ BEGIN
  CREATE TYPE "HomeworkGradingType" AS ENUM ('MARKS', 'PERCENTAGE', 'GRADE', 'RUBRIC', 'PASS_FAIL');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;
  ALTER TYPE "HomeworkGradingType" ADD VALUE IF NOT EXISTS 'MARKS';
  ALTER TYPE "HomeworkGradingType" ADD VALUE IF NOT EXISTS 'PERCENTAGE';
  ALTER TYPE "HomeworkGradingType" ADD VALUE IF NOT EXISTS 'GRADE';
  ALTER TYPE "HomeworkGradingType" ADD VALUE IF NOT EXISTS 'RUBRIC';
  ALTER TYPE "HomeworkGradingType" ADD VALUE IF NOT EXISTS 'PASS_FAIL';

DO $$ BEGIN
  CREATE TYPE "HomeworkSubmissionStatus" AS ENUM ('PENDING', 'SUBMITTED', 'LATE', 'RETURNED', 'GRADED', 'COMPLETED');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;
  ALTER TYPE "HomeworkSubmissionStatus" ADD VALUE IF NOT EXISTS 'PENDING';
  ALTER TYPE "HomeworkSubmissionStatus" ADD VALUE IF NOT EXISTS 'SUBMITTED';
  ALTER TYPE "HomeworkSubmissionStatus" ADD VALUE IF NOT EXISTS 'LATE';
  ALTER TYPE "HomeworkSubmissionStatus" ADD VALUE IF NOT EXISTS 'RETURNED';
  ALTER TYPE "HomeworkSubmissionStatus" ADD VALUE IF NOT EXISTS 'GRADED';
  ALTER TYPE "HomeworkSubmissionStatus" ADD VALUE IF NOT EXISTS 'COMPLETED';

DO $$ BEGIN
  CREATE TYPE "MeetingProvider" AS ENUM ('ZOOM', 'GOOGLE_MEET', 'MICROSOFT_TEAMS', 'CUSTOM');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;
  ALTER TYPE "MeetingProvider" ADD VALUE IF NOT EXISTS 'ZOOM';
  ALTER TYPE "MeetingProvider" ADD VALUE IF NOT EXISTS 'GOOGLE_MEET';
  ALTER TYPE "MeetingProvider" ADD VALUE IF NOT EXISTS 'MICROSOFT_TEAMS';
  ALTER TYPE "MeetingProvider" ADD VALUE IF NOT EXISTS 'CUSTOM';

DO $$ BEGIN
  CREATE TYPE "OnlineClassStatus" AS ENUM ('SCHEDULED', 'LIVE', 'COMPLETED', 'CANCELLED');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;
  ALTER TYPE "OnlineClassStatus" ADD VALUE IF NOT EXISTS 'SCHEDULED';
  ALTER TYPE "OnlineClassStatus" ADD VALUE IF NOT EXISTS 'LIVE';
  ALTER TYPE "OnlineClassStatus" ADD VALUE IF NOT EXISTS 'COMPLETED';
  ALTER TYPE "OnlineClassStatus" ADD VALUE IF NOT EXISTS 'CANCELLED';

DO $$ BEGIN
  CREATE TYPE "OnlineAttendanceStatus" AS ENUM ('PRESENT', 'ABSENT', 'LATE', 'EXCUSED');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;
  ALTER TYPE "OnlineAttendanceStatus" ADD VALUE IF NOT EXISTS 'PRESENT';
  ALTER TYPE "OnlineAttendanceStatus" ADD VALUE IF NOT EXISTS 'ABSENT';
  ALTER TYPE "OnlineAttendanceStatus" ADD VALUE IF NOT EXISTS 'LATE';
  ALTER TYPE "OnlineAttendanceStatus" ADD VALUE IF NOT EXISTS 'EXCUSED';

DO $$ BEGIN
  CREATE TYPE "OnlineAttendanceSource" AS ENUM ('MANUAL', 'AUTO');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;
  ALTER TYPE "OnlineAttendanceSource" ADD VALUE IF NOT EXISTS 'MANUAL';
  ALTER TYPE "OnlineAttendanceSource" ADD VALUE IF NOT EXISTS 'AUTO';

DO $$ BEGIN
  CREATE TYPE "CalendarEventType" AS ENUM ('ACADEMIC_SESSION', 'HOLIDAY', 'SCHOOL_EVENT', 'SPORTS_DAY', 'ANNUAL_FUNCTION', 'PTM', 'EXAM_SCHEDULE', 'RESULT_DAY', 'FEE_DUE_DATE', 'ADMISSION_DEADLINE', 'TEACHER_MEETING', 'STAFF_MEETING', 'HOMEWORK_DEADLINE', 'ONLINE_CLASS', 'CUSTOM');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;
  ALTER TYPE "CalendarEventType" ADD VALUE IF NOT EXISTS 'ACADEMIC_SESSION';
  ALTER TYPE "CalendarEventType" ADD VALUE IF NOT EXISTS 'HOLIDAY';
  ALTER TYPE "CalendarEventType" ADD VALUE IF NOT EXISTS 'SCHOOL_EVENT';
  ALTER TYPE "CalendarEventType" ADD VALUE IF NOT EXISTS 'SPORTS_DAY';
  ALTER TYPE "CalendarEventType" ADD VALUE IF NOT EXISTS 'ANNUAL_FUNCTION';
  ALTER TYPE "CalendarEventType" ADD VALUE IF NOT EXISTS 'PTM';
  ALTER TYPE "CalendarEventType" ADD VALUE IF NOT EXISTS 'EXAM_SCHEDULE';
  ALTER TYPE "CalendarEventType" ADD VALUE IF NOT EXISTS 'RESULT_DAY';
  ALTER TYPE "CalendarEventType" ADD VALUE IF NOT EXISTS 'FEE_DUE_DATE';
  ALTER TYPE "CalendarEventType" ADD VALUE IF NOT EXISTS 'ADMISSION_DEADLINE';
  ALTER TYPE "CalendarEventType" ADD VALUE IF NOT EXISTS 'TEACHER_MEETING';
  ALTER TYPE "CalendarEventType" ADD VALUE IF NOT EXISTS 'STAFF_MEETING';
  ALTER TYPE "CalendarEventType" ADD VALUE IF NOT EXISTS 'HOMEWORK_DEADLINE';
  ALTER TYPE "CalendarEventType" ADD VALUE IF NOT EXISTS 'ONLINE_CLASS';
  ALTER TYPE "CalendarEventType" ADD VALUE IF NOT EXISTS 'CUSTOM';

DO $$ BEGIN
  CREATE TYPE "CalendarEventStatus" AS ENUM ('DRAFT', 'PUBLISHED', 'CANCELLED');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;
  ALTER TYPE "CalendarEventStatus" ADD VALUE IF NOT EXISTS 'DRAFT';
  ALTER TYPE "CalendarEventStatus" ADD VALUE IF NOT EXISTS 'PUBLISHED';
  ALTER TYPE "CalendarEventStatus" ADD VALUE IF NOT EXISTS 'CANCELLED';

DO $$ BEGIN
  CREATE TYPE "CalendarRecurrence" AS ENUM ('NONE', 'DAILY', 'WEEKLY', 'MONTHLY', 'YEARLY');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;
  ALTER TYPE "CalendarRecurrence" ADD VALUE IF NOT EXISTS 'NONE';
  ALTER TYPE "CalendarRecurrence" ADD VALUE IF NOT EXISTS 'DAILY';
  ALTER TYPE "CalendarRecurrence" ADD VALUE IF NOT EXISTS 'WEEKLY';
  ALTER TYPE "CalendarRecurrence" ADD VALUE IF NOT EXISTS 'MONTHLY';
  ALTER TYPE "CalendarRecurrence" ADD VALUE IF NOT EXISTS 'YEARLY';

-- Align existing table "School"
ALTER TABLE "School" ADD COLUMN IF NOT EXISTS "id" TEXT NOT NULL;
ALTER TABLE "School" ADD COLUMN IF NOT EXISTS "name" TEXT NOT NULL;
ALTER TABLE "School" ADD COLUMN IF NOT EXISTS "slug" TEXT NOT NULL;
ALTER TABLE "School" ADD COLUMN IF NOT EXISTS "domain" TEXT;
ALTER TABLE "School" ADD COLUMN IF NOT EXISTS "status" "SchoolStatus" NOT NULL DEFAULT 'ACTIVE';
ALTER TABLE "School" ADD COLUMN IF NOT EXISTS "ownerName" TEXT;
ALTER TABLE "School" ADD COLUMN IF NOT EXISTS "address" TEXT;
ALTER TABLE "School" ADD COLUMN IF NOT EXISTS "phone" TEXT;
ALTER TABLE "School" ADD COLUMN IF NOT EXISTS "email" TEXT;
ALTER TABLE "School" ADD COLUMN IF NOT EXISTS "logoUrl" TEXT;
ALTER TABLE "School" ADD COLUMN IF NOT EXISTS "themeColor" TEXT;
ALTER TABLE "School" ADD COLUMN IF NOT EXISTS "emailNotificationsEnabled" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "School" ADD COLUMN IF NOT EXISTS "smsNotificationsEnabled" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "School" ADD COLUMN IF NOT EXISTS "whatsappNotificationsEnabled" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "School" ADD COLUMN IF NOT EXISTS "disabledRoles" "UserRole"[] DEFAULT ARRAY[]::"UserRole"[];
ALTER TABLE "School" ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "School" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP(3) NOT NULL;

CREATE TABLE IF NOT EXISTS "SubscriptionPlan" (
    "id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "tier" "PlanTier" NOT NULL,
    "priceMonthly" DECIMAL(10,2) NOT NULL DEFAULT 0,
    "priceAnnually" DECIMAL(10,2) NOT NULL DEFAULT 0,
    "maxStudents" INTEGER NOT NULL DEFAULT 0,
    "maxTeachers" INTEGER NOT NULL DEFAULT 0,
    "features" JSONB NOT NULL DEFAULT '[]',
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "SubscriptionPlan_pkey" PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "SchoolSubscription" (
    "id" TEXT NOT NULL,
    "schoolId" TEXT NOT NULL,
    "planId" TEXT NOT NULL,
    "status" "SubscriptionStatus" NOT NULL DEFAULT 'TRIAL',
    "startDate" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "endDate" TIMESTAMP(3),
    "autoRenew" BOOLEAN NOT NULL DEFAULT false,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "SchoolSubscription_pkey" PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "SaasInvoice" (
    "id" TEXT NOT NULL,
    "invoiceNo" TEXT NOT NULL,
    "schoolId" TEXT NOT NULL,
    "subscriptionId" TEXT NOT NULL,
    "amount" DECIMAL(10,2) NOT NULL,
    "currency" TEXT NOT NULL DEFAULT 'PKR',
    "status" "SaasInvoiceStatus" NOT NULL DEFAULT 'PENDING',
    "dueDate" TIMESTAMP(3) NOT NULL,
    "paidAt" TIMESTAMP(3),
    "period" TEXT NOT NULL,
    "notes" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "SaasInvoice_pkey" PRIMARY KEY ("id")
);

-- Recreate AuditLog only when the legacy (pre-platform) columns are present.
DO $$ BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'AuditLog' AND column_name = 'module'
  ) THEN
    DROP TABLE "AuditLog";
  END IF;
END $$;
CREATE TABLE IF NOT EXISTS "AuditLog" (
    "id" TEXT NOT NULL,
    "action" "AuditAction" NOT NULL,
    "actorId" TEXT,
    "actorName" TEXT,
    "schoolId" TEXT,
    "schoolName" TEXT,
    "metadata" JSONB DEFAULT '{}',
    "ip" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "AuditLog_pkey" PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "PlatformSetting" (
    "id" TEXT NOT NULL,
    "key" TEXT NOT NULL,
    "value" TEXT NOT NULL,
    "label" TEXT NOT NULL,
    "category" TEXT NOT NULL DEFAULT 'general',
    "isSecret" BOOLEAN NOT NULL DEFAULT false,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "PlatformSetting_pkey" PRIMARY KEY ("id")
);

-- Align existing table "User"
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "id" TEXT NOT NULL;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "schoolId" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "name" TEXT NOT NULL;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "email" TEXT NOT NULL;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "phone" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "password" TEXT NOT NULL;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "role" "UserRole" NOT NULL;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "status" "UserStatus" NOT NULL DEFAULT 'ACTIVE';
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "loginAttempts" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "lockedUntil" TIMESTAMP(3);
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "lastLoginAt" TIMESTAMP(3);
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "forcePasswordChange" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "passwordResetToken" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "passwordResetExpiresAt" TIMESTAMP(3);
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "customRoleId" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP(3) NOT NULL;

CREATE TABLE IF NOT EXISTS "RefreshToken" (
    "id" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "tokenHash" TEXT NOT NULL,
    "expiresAt" TIMESTAMP(3) NOT NULL,
    "revokedAt" TIMESTAMP(3),
    "ipAddress" TEXT,
    "userAgent" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "RefreshToken_pkey" PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "LoginOtpChallenge" (
    "id" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "purpose" TEXT NOT NULL DEFAULT 'LOGIN',
    "codeHash" TEXT NOT NULL,
    "expiresAt" TIMESTAMP(3) NOT NULL,
    "attempts" INTEGER NOT NULL DEFAULT 0,
    "maxAttempts" INTEGER NOT NULL DEFAULT 5,
    "usedAt" TIMESTAMP(3),
    "lastSentAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "ipAddress" TEXT,
    "userAgent" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "LoginOtpChallenge_pkey" PRIMARY KEY ("id")
);

-- Align existing table "Class"
ALTER TABLE "Class" ADD COLUMN IF NOT EXISTS "id" TEXT NOT NULL;
ALTER TABLE "Class" ADD COLUMN IF NOT EXISTS "schoolId" TEXT NOT NULL;
ALTER TABLE "Class" ADD COLUMN IF NOT EXISTS "name" TEXT NOT NULL;
ALTER TABLE "Class" ADD COLUMN IF NOT EXISTS "classTeacherId" TEXT;
ALTER TABLE "Class" ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "Class" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP(3) NOT NULL;

-- Align existing table "Section"
ALTER TABLE "Section" ADD COLUMN IF NOT EXISTS "id" TEXT NOT NULL;
ALTER TABLE "Section" ADD COLUMN IF NOT EXISTS "schoolId" TEXT NOT NULL;
ALTER TABLE "Section" ADD COLUMN IF NOT EXISTS "name" TEXT NOT NULL;
ALTER TABLE "Section" ADD COLUMN IF NOT EXISTS "classId" TEXT NOT NULL;
ALTER TABLE "Section" ADD COLUMN IF NOT EXISTS "teacherId" TEXT;
ALTER TABLE "Section" ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "Section" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP(3) NOT NULL;

-- Align existing table "Subject"
ALTER TABLE "Subject" ADD COLUMN IF NOT EXISTS "id" TEXT NOT NULL;
ALTER TABLE "Subject" ADD COLUMN IF NOT EXISTS "schoolId" TEXT NOT NULL;
ALTER TABLE "Subject" ADD COLUMN IF NOT EXISTS "name" TEXT NOT NULL;
ALTER TABLE "Subject" ADD COLUMN IF NOT EXISTS "code" TEXT;
ALTER TABLE "Subject" ADD COLUMN IF NOT EXISTS "classId" TEXT;
ALTER TABLE "Subject" ADD COLUMN IF NOT EXISTS "sectionId" TEXT;
ALTER TABLE "Subject" ADD COLUMN IF NOT EXISTS "teacherId" TEXT;
ALTER TABLE "Subject" ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "Subject" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP(3) NOT NULL;

-- Align existing table "Student"
ALTER TABLE "Student" ADD COLUMN IF NOT EXISTS "id" TEXT NOT NULL;
ALTER TABLE "Student" ADD COLUMN IF NOT EXISTS "schoolId" TEXT NOT NULL;
ALTER TABLE "Student" ADD COLUMN IF NOT EXISTS "userId" TEXT;
ALTER TABLE "Student" ADD COLUMN IF NOT EXISTS "admissionNo" TEXT NOT NULL;
ALTER TABLE "Student" ADD COLUMN IF NOT EXISTS "admissionDate" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "Student" ADD COLUMN IF NOT EXISTS "fullName" TEXT NOT NULL;
ALTER TABLE "Student" ADD COLUMN IF NOT EXISTS "fatherName" TEXT;
ALTER TABLE "Student" ADD COLUMN IF NOT EXISTS "guardianPhone" TEXT;
ALTER TABLE "Student" ADD COLUMN IF NOT EXISTS "whatsappNumber" TEXT;
ALTER TABLE "Student" ADD COLUMN IF NOT EXISTS "gender" TEXT;
ALTER TABLE "Student" ADD COLUMN IF NOT EXISTS "dateOfBirth" TIMESTAMP(3);
ALTER TABLE "Student" ADD COLUMN IF NOT EXISTS "address" TEXT;
ALTER TABLE "Student" ADD COLUMN IF NOT EXISTS "photoUrl" TEXT;
ALTER TABLE "Student" ADD COLUMN IF NOT EXISTS "status" TEXT NOT NULL DEFAULT 'ACTIVE';
ALTER TABLE "Student" ADD COLUMN IF NOT EXISTS "classId" TEXT;
ALTER TABLE "Student" ADD COLUMN IF NOT EXISTS "sectionId" TEXT;
ALTER TABLE "Student" ADD COLUMN IF NOT EXISTS "monthlyFee" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Student" ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "Student" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP(3) NOT NULL;

-- Align existing table "Exam"
ALTER TABLE "Exam" ADD COLUMN IF NOT EXISTS "id" TEXT NOT NULL;
ALTER TABLE "Exam" ADD COLUMN IF NOT EXISTS "schoolId" TEXT NOT NULL;
ALTER TABLE "Exam" ADD COLUMN IF NOT EXISTS "name" TEXT NOT NULL;
ALTER TABLE "Exam" ADD COLUMN IF NOT EXISTS "classId" TEXT NOT NULL;
ALTER TABLE "Exam" ADD COLUMN IF NOT EXISTS "sectionId" TEXT;
ALTER TABLE "Exam" ADD COLUMN IF NOT EXISTS "startDate" TIMESTAMP(3);
ALTER TABLE "Exam" ADD COLUMN IF NOT EXISTS "endDate" TIMESTAMP(3);
ALTER TABLE "Exam" ADD COLUMN IF NOT EXISTS "status" "ExamStatus" NOT NULL DEFAULT 'DRAFT';
ALTER TABLE "Exam" ADD COLUMN IF NOT EXISTS "description" TEXT;
ALTER TABLE "Exam" ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "Exam" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP(3) NOT NULL;

-- Align existing table "ExamSubject"
ALTER TABLE "ExamSubject" ADD COLUMN IF NOT EXISTS "id" TEXT NOT NULL;
ALTER TABLE "ExamSubject" ADD COLUMN IF NOT EXISTS "schoolId" TEXT NOT NULL;
ALTER TABLE "ExamSubject" ADD COLUMN IF NOT EXISTS "examId" TEXT NOT NULL;
ALTER TABLE "ExamSubject" ADD COLUMN IF NOT EXISTS "subjectId" TEXT NOT NULL;
ALTER TABLE "ExamSubject" ADD COLUMN IF NOT EXISTS "totalMarks" INTEGER NOT NULL;
ALTER TABLE "ExamSubject" ADD COLUMN IF NOT EXISTS "passingMarks" INTEGER NOT NULL;
ALTER TABLE "ExamSubject" ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "ExamSubject" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP(3) NOT NULL;

-- Align existing table "Mark"
ALTER TABLE "Mark" ADD COLUMN IF NOT EXISTS "id" TEXT NOT NULL;
ALTER TABLE "Mark" ADD COLUMN IF NOT EXISTS "schoolId" TEXT NOT NULL;
ALTER TABLE "Mark" ADD COLUMN IF NOT EXISTS "examId" TEXT NOT NULL;
ALTER TABLE "Mark" ADD COLUMN IF NOT EXISTS "subjectId" TEXT NOT NULL;
ALTER TABLE "Mark" ADD COLUMN IF NOT EXISTS "studentId" TEXT NOT NULL;
ALTER TABLE "Mark" ADD COLUMN IF NOT EXISTS "obtainedMarks" INTEGER NOT NULL;
ALTER TABLE "Mark" ADD COLUMN IF NOT EXISTS "remarks" TEXT;
ALTER TABLE "Mark" ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "Mark" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP(3) NOT NULL;

-- Align existing table "Grade"
ALTER TABLE "Grade" ADD COLUMN IF NOT EXISTS "id" TEXT NOT NULL;
ALTER TABLE "Grade" ADD COLUMN IF NOT EXISTS "schoolId" TEXT NOT NULL;
ALTER TABLE "Grade" ADD COLUMN IF NOT EXISTS "name" TEXT NOT NULL;
ALTER TABLE "Grade" ADD COLUMN IF NOT EXISTS "minPercent" INTEGER NOT NULL;
ALTER TABLE "Grade" ADD COLUMN IF NOT EXISTS "maxPercent" INTEGER NOT NULL;
ALTER TABLE "Grade" ADD COLUMN IF NOT EXISTS "remarks" TEXT;
ALTER TABLE "Grade" ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "Grade" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP(3) NOT NULL;

-- Align existing table "StudentAttendance"
ALTER TABLE "StudentAttendance" ADD COLUMN IF NOT EXISTS "id" TEXT NOT NULL;
ALTER TABLE "StudentAttendance" ADD COLUMN IF NOT EXISTS "schoolId" TEXT NOT NULL;
ALTER TABLE "StudentAttendance" ADD COLUMN IF NOT EXISTS "studentId" TEXT NOT NULL;
ALTER TABLE "StudentAttendance" ADD COLUMN IF NOT EXISTS "classId" TEXT;
ALTER TABLE "StudentAttendance" ADD COLUMN IF NOT EXISTS "sectionId" TEXT;
ALTER TABLE "StudentAttendance" ADD COLUMN IF NOT EXISTS "date" TIMESTAMP(3) NOT NULL;
ALTER TABLE "StudentAttendance" ADD COLUMN IF NOT EXISTS "status" "AttendanceStatus" NOT NULL;
ALTER TABLE "StudentAttendance" ADD COLUMN IF NOT EXISTS "remarks" TEXT;
ALTER TABLE "StudentAttendance" ADD COLUMN IF NOT EXISTS "markedById" TEXT;
ALTER TABLE "StudentAttendance" ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "StudentAttendance" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP(3) NOT NULL;

-- Align existing table "FeeStructure"
ALTER TABLE "FeeStructure" ADD COLUMN IF NOT EXISTS "id" TEXT NOT NULL;
ALTER TABLE "FeeStructure" ADD COLUMN IF NOT EXISTS "schoolId" TEXT NOT NULL;
ALTER TABLE "FeeStructure" ADD COLUMN IF NOT EXISTS "classId" TEXT;
ALTER TABLE "FeeStructure" ADD COLUMN IF NOT EXISTS "title" TEXT NOT NULL;
ALTER TABLE "FeeStructure" ADD COLUMN IF NOT EXISTS "amount" INTEGER NOT NULL;
ALTER TABLE "FeeStructure" ADD COLUMN IF NOT EXISTS "description" TEXT;
ALTER TABLE "FeeStructure" ADD COLUMN IF NOT EXISTS "isActive" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "FeeStructure" ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "FeeStructure" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP(3) NOT NULL;

-- Align existing table "FeeInvoice"
ALTER TABLE "FeeInvoice" ADD COLUMN IF NOT EXISTS "id" TEXT NOT NULL;
ALTER TABLE "FeeInvoice" ADD COLUMN IF NOT EXISTS "schoolId" TEXT NOT NULL;
ALTER TABLE "FeeInvoice" ADD COLUMN IF NOT EXISTS "studentId" TEXT NOT NULL;
ALTER TABLE "FeeInvoice" ADD COLUMN IF NOT EXISTS "invoiceNo" TEXT NOT NULL;
ALTER TABLE "FeeInvoice" ADD COLUMN IF NOT EXISTS "month" INTEGER NOT NULL;
ALTER TABLE "FeeInvoice" ADD COLUMN IF NOT EXISTS "year" INTEGER NOT NULL;
ALTER TABLE "FeeInvoice" ADD COLUMN IF NOT EXISTS "amount" INTEGER NOT NULL;
ALTER TABLE "FeeInvoice" ADD COLUMN IF NOT EXISTS "discount" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "FeeInvoice" ADD COLUMN IF NOT EXISTS "fine" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "FeeInvoice" ADD COLUMN IF NOT EXISTS "totalAmount" INTEGER NOT NULL;
ALTER TABLE "FeeInvoice" ADD COLUMN IF NOT EXISTS "paidAmount" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "FeeInvoice" ADD COLUMN IF NOT EXISTS "status" "FeeInvoiceStatus" NOT NULL DEFAULT 'UNPAID';
ALTER TABLE "FeeInvoice" ADD COLUMN IF NOT EXISTS "dueDate" TIMESTAMP(3);
ALTER TABLE "FeeInvoice" ADD COLUMN IF NOT EXISTS "notes" TEXT;
ALTER TABLE "FeeInvoice" ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "FeeInvoice" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP(3) NOT NULL;

-- Align existing table "FeePayment"
ALTER TABLE "FeePayment" ADD COLUMN IF NOT EXISTS "id" TEXT NOT NULL;
ALTER TABLE "FeePayment" ADD COLUMN IF NOT EXISTS "schoolId" TEXT NOT NULL;
ALTER TABLE "FeePayment" ADD COLUMN IF NOT EXISTS "invoiceId" TEXT NOT NULL;
ALTER TABLE "FeePayment" ADD COLUMN IF NOT EXISTS "receiptNo" TEXT NOT NULL;
ALTER TABLE "FeePayment" ADD COLUMN IF NOT EXISTS "amount" INTEGER NOT NULL;
ALTER TABLE "FeePayment" ADD COLUMN IF NOT EXISTS "paymentDate" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "FeePayment" ADD COLUMN IF NOT EXISTS "method" TEXT;
ALTER TABLE "FeePayment" ADD COLUMN IF NOT EXISTS "notes" TEXT;
ALTER TABLE "FeePayment" ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "FeePayment" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP(3) NOT NULL;

-- Align existing table "Teacher"
ALTER TABLE "Teacher" ADD COLUMN IF NOT EXISTS "id" TEXT NOT NULL;
ALTER TABLE "Teacher" ADD COLUMN IF NOT EXISTS "schoolId" TEXT NOT NULL;
ALTER TABLE "Teacher" ADD COLUMN IF NOT EXISTS "userId" TEXT;
ALTER TABLE "Teacher" ADD COLUMN IF NOT EXISTS "fullName" TEXT NOT NULL;
ALTER TABLE "Teacher" ADD COLUMN IF NOT EXISTS "phone" TEXT;
ALTER TABLE "Teacher" ADD COLUMN IF NOT EXISTS "email" TEXT;
ALTER TABLE "Teacher" ADD COLUMN IF NOT EXISTS "address" TEXT;
ALTER TABLE "Teacher" ADD COLUMN IF NOT EXISTS "salary" INTEGER;
ALTER TABLE "Teacher" ADD COLUMN IF NOT EXISTS "status" TEXT NOT NULL DEFAULT 'ACTIVE';
ALTER TABLE "Teacher" ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "Teacher" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP(3) NOT NULL;

-- Align existing table "Parent"
ALTER TABLE "Parent" ADD COLUMN IF NOT EXISTS "id" TEXT NOT NULL;
ALTER TABLE "Parent" ADD COLUMN IF NOT EXISTS "schoolId" TEXT NOT NULL;
ALTER TABLE "Parent" ADD COLUMN IF NOT EXISTS "userId" TEXT;
ALTER TABLE "Parent" ADD COLUMN IF NOT EXISTS "studentId" TEXT;
ALTER TABLE "Parent" ADD COLUMN IF NOT EXISTS "fullName" TEXT NOT NULL;
ALTER TABLE "Parent" ADD COLUMN IF NOT EXISTS "phone" TEXT;
ALTER TABLE "Parent" ADD COLUMN IF NOT EXISTS "email" TEXT;
ALTER TABLE "Parent" ADD COLUMN IF NOT EXISTS "address" TEXT;
ALTER TABLE "Parent" ADD COLUMN IF NOT EXISTS "status" TEXT NOT NULL DEFAULT 'ACTIVE';
ALTER TABLE "Parent" ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "Parent" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP(3) NOT NULL;

CREATE TABLE IF NOT EXISTS "Staff" (
    "id" TEXT NOT NULL,
    "schoolId" TEXT NOT NULL,
    "userId" TEXT,
    "fullName" TEXT NOT NULL,
    "designation" TEXT,
    "department" TEXT,
    "phone" TEXT,
    "email" TEXT,
    "address" TEXT,
    "joiningDate" TIMESTAMP(3),
    "salary" INTEGER,
    "status" TEXT NOT NULL DEFAULT 'ACTIVE',
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Staff_pkey" PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "ExpenseCategory" (
    "id" TEXT NOT NULL,
    "schoolId" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "description" TEXT,
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "ExpenseCategory_pkey" PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "Expense" (
    "id" TEXT NOT NULL,
    "schoolId" TEXT NOT NULL,
    "categoryId" TEXT NOT NULL,
    "title" TEXT NOT NULL,
    "amount" INTEGER NOT NULL,
    "date" TIMESTAMP(3) NOT NULL,
    "description" TEXT,
    "receiptUrl" TEXT,
    "status" TEXT NOT NULL DEFAULT 'ACTIVE',
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Expense_pkey" PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "Payroll" (
    "id" TEXT NOT NULL,
    "schoolId" TEXT NOT NULL,
    "staffType" "StaffType" NOT NULL,
    "teacherId" TEXT,
    "staffId" TEXT,
    "staffName" TEXT NOT NULL,
    "month" INTEGER NOT NULL,
    "year" INTEGER NOT NULL,
    "basicSalary" INTEGER NOT NULL,
    "allowances" INTEGER NOT NULL DEFAULT 0,
    "deductions" INTEGER NOT NULL DEFAULT 0,
    "netSalary" INTEGER NOT NULL,
    "status" "PayrollStatus" NOT NULL DEFAULT 'PENDING',
    "paidAt" TIMESTAMP(3),
    "paidById" TEXT,
    "notes" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Payroll_pkey" PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "TimetableEntry" (
    "id" TEXT NOT NULL,
    "schoolId" TEXT NOT NULL,
    "classId" TEXT NOT NULL,
    "sectionId" TEXT,
    "subjectId" TEXT,
    "teacherId" TEXT,
    "dayOfWeek" INTEGER NOT NULL,
    "periodNo" INTEGER NOT NULL,
    "startTime" TEXT NOT NULL,
    "endTime" TEXT NOT NULL,
    "roomNo" TEXT,
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "TimetableEntry_pkey" PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "BookCategory" (
    "id" TEXT NOT NULL,
    "schoolId" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "description" TEXT,
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "BookCategory_pkey" PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "Book" (
    "id" TEXT NOT NULL,
    "schoolId" TEXT NOT NULL,
    "categoryId" TEXT NOT NULL,
    "title" TEXT NOT NULL,
    "author" TEXT,
    "isbn" TEXT,
    "publisher" TEXT,
    "edition" TEXT,
    "totalCopies" INTEGER NOT NULL DEFAULT 1,
    "availableCopies" INTEGER NOT NULL DEFAULT 1,
    "shelfLocation" TEXT,
    "status" TEXT NOT NULL DEFAULT 'ACTIVE',
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Book_pkey" PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "BookIssue" (
    "id" TEXT NOT NULL,
    "schoolId" TEXT NOT NULL,
    "bookId" TEXT NOT NULL,
    "studentId" TEXT,
    "issuedToName" TEXT NOT NULL,
    "issueDate" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "dueDate" TIMESTAMP(3) NOT NULL,
    "returnDate" TIMESTAMP(3),
    "fine" INTEGER NOT NULL DEFAULT 0,
    "finePaid" BOOLEAN NOT NULL DEFAULT false,
    "status" TEXT NOT NULL DEFAULT 'ISSUED',
    "remarks" TEXT,
    "issuedById" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "BookIssue_pkey" PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "Vehicle" (
    "id" TEXT NOT NULL,
    "schoolId" TEXT NOT NULL,
    "vehicleNo" TEXT NOT NULL,
    "type" TEXT NOT NULL DEFAULT 'BUS',
    "capacity" INTEGER NOT NULL,
    "driverName" TEXT,
    "driverPhone" TEXT,
    "model" TEXT,
    "status" TEXT NOT NULL DEFAULT 'ACTIVE',
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Vehicle_pkey" PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "TransportRoute" (
    "id" TEXT NOT NULL,
    "schoolId" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "vehicleId" TEXT,
    "startPoint" TEXT NOT NULL,
    "endPoint" TEXT NOT NULL,
    "stops" TEXT,
    "fare" INTEGER,
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "TransportRoute_pkey" PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "StudentTransport" (
    "id" TEXT NOT NULL,
    "schoolId" TEXT NOT NULL,
    "studentId" TEXT NOT NULL,
    "routeId" TEXT NOT NULL,
    "pickupPoint" TEXT,
    "dropPoint" TEXT,
    "monthlyFee" INTEGER NOT NULL DEFAULT 0,
    "status" TEXT NOT NULL DEFAULT 'ACTIVE',
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "StudentTransport_pkey" PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "Notice" (
    "id" TEXT NOT NULL,
    "schoolId" TEXT NOT NULL,
    "title" TEXT NOT NULL,
    "content" TEXT NOT NULL,
    "type" TEXT NOT NULL DEFAULT 'NOTICE',
    "targetRoles" TEXT,
    "startDate" TIMESTAMP(3),
    "endDate" TIMESTAMP(3),
    "isPublished" BOOLEAN NOT NULL DEFAULT false,
    "attachmentUrl" TEXT,
    "createdById" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Notice_pkey" PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "StudentDocument" (
    "id" TEXT NOT NULL,
    "schoolId" TEXT NOT NULL,
    "studentId" TEXT NOT NULL,
    "type" "DocumentType" NOT NULL,
    "fileName" TEXT NOT NULL,
    "fileUrl" TEXT NOT NULL,
    "fileSize" INTEGER,
    "mimeType" TEXT,
    "uploadedById" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "StudentDocument_pkey" PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "SchoolAuditLog" (
    "id" TEXT NOT NULL,
    "schoolId" TEXT NOT NULL,
    "userId" TEXT,
    "actorName" TEXT,
    "action" TEXT NOT NULL,
    "entity" TEXT,
    "entityId" TEXT,
    "description" TEXT,
    "details" JSONB,
    "oldValue" JSONB,
    "newValue" JSONB,
    "changedFields" JSONB,
    "ipAddress" TEXT,
    "userAgent" TEXT,
    "dedupeKey" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "SchoolAuditLog_pkey" PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "NotificationLog" (
    "id" TEXT NOT NULL,
    "schoolId" TEXT,
    "eventType" TEXT,
    "channel" "NotificationChannel" NOT NULL,
    "recipient" TEXT NOT NULL,
    "subject" TEXT,
    "body" TEXT NOT NULL,
    "status" "NotificationStatus" NOT NULL DEFAULT 'PENDING',
    "error" TEXT,
    "sentAt" TIMESTAMP(3),
    "deliveredAt" TIMESTAMP(3),
    "readAt" TIMESTAMP(3),
    "senderId" TEXT,
    "campaignId" TEXT,
    "templateId" TEXT,
    "retryCount" INTEGER NOT NULL DEFAULT 0,
    "providerMessageId" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "NotificationLog_pkey" PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "UserNotification" (
    "id" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "schoolId" TEXT,
    "eventType" TEXT NOT NULL,
    "title" TEXT NOT NULL,
    "body" TEXT NOT NULL,
    "type" "NotificationSeverity" NOT NULL DEFAULT 'INFO',
    "category" "NotificationCategory" NOT NULL DEFAULT 'SYSTEM',
    "linkUrl" TEXT,
    "dedupeKey" TEXT,
    "isRead" BOOLEAN NOT NULL DEFAULT false,
    "readAt" TIMESTAMP(3),
    "isArchived" BOOLEAN NOT NULL DEFAULT false,
    "archivedAt" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "UserNotification_pkey" PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "NotificationPreference" (
    "id" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "category" "NotificationCategory" NOT NULL,
    "inAppEnabled" BOOLEAN NOT NULL DEFAULT true,
    "emailEnabled" BOOLEAN NOT NULL DEFAULT true,
    "smsEnabled" BOOLEAN NOT NULL DEFAULT false,
    "pushEnabled" BOOLEAN NOT NULL DEFAULT false,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "NotificationPreference_pkey" PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "NotificationTemplate" (
    "id" TEXT NOT NULL,
    "schoolId" TEXT,
    "code" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "category" "NotificationCategory" NOT NULL DEFAULT 'ANNOUNCEMENT',
    "channel" "NotificationChannel" NOT NULL DEFAULT 'IN_APP',
    "subject" TEXT,
    "body" TEXT NOT NULL,
    "isDefault" BOOLEAN NOT NULL DEFAULT false,
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "NotificationTemplate_pkey" PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "NotificationCampaign" (
    "id" TEXT NOT NULL,
    "schoolId" TEXT,
    "createdById" TEXT NOT NULL,
    "title" TEXT NOT NULL,
    "subject" TEXT,
    "body" TEXT NOT NULL,
    "templateId" TEXT,
    "category" "NotificationCategory" NOT NULL DEFAULT 'ANNOUNCEMENT',
    "channels" JSONB NOT NULL DEFAULT '[]',
    "audienceType" "CampaignAudience" NOT NULL,
    "audienceFilter" JSONB NOT NULL DEFAULT '{}',
    "status" "CampaignStatus" NOT NULL DEFAULT 'DRAFT',
    "scheduledAt" TIMESTAMP(3),
    "recurrence" "RecurrenceType" NOT NULL DEFAULT 'NONE',
    "nextRunAt" TIMESTAMP(3),
    "sentAt" TIMESTAMP(3),
    "retryFailed" BOOLEAN NOT NULL DEFAULT true,
    "maxRetries" INTEGER NOT NULL DEFAULT 3,
    "stats" JSONB,
    "error" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "NotificationCampaign_pkey" PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "PushDeviceToken" (
    "id" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "token" TEXT NOT NULL,
    "platform" "PushPlatform" NOT NULL DEFAULT 'WEB',
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "lastUsedAt" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "PushDeviceToken_pkey" PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "RolePermission" (
    "id" TEXT NOT NULL,
    "schoolId" TEXT NOT NULL,
    "role" "UserRole" NOT NULL,
    "permissions" JSONB NOT NULL DEFAULT '{}',
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "RolePermission_pkey" PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "SchoolCustomRole" (
    "id" TEXT NOT NULL,
    "schoolId" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "slug" TEXT NOT NULL,
    "description" TEXT,
    "baseRole" "UserRole" NOT NULL,
    "permissions" JSONB NOT NULL DEFAULT '{}',
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "SchoolCustomRole_pkey" PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "Homework" (
    "id" TEXT NOT NULL,
    "schoolId" TEXT NOT NULL,
    "title" TEXT NOT NULL,
    "subjectId" TEXT,
    "classId" TEXT NOT NULL,
    "sectionId" TEXT,
    "teacherId" TEXT,
    "academicSession" TEXT,
    "dueDate" TIMESTAMP(3) NOT NULL,
    "instructions" TEXT,
    "description" TEXT,
    "priority" "HomeworkPriority" NOT NULL DEFAULT 'MEDIUM',
    "estimatedMinutes" INTEGER,
    "status" "HomeworkStatus" NOT NULL DEFAULT 'DRAFT',
    "gradingType" "HomeworkGradingType" NOT NULL DEFAULT 'MARKS',
    "maxMarks" DOUBLE PRECISION,
    "allowResubmit" BOOLEAN NOT NULL DEFAULT true,
    "rubric" JSONB,
    "createdById" TEXT,
    "onlineClassId" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Homework_pkey" PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "HomeworkAttachment" (
    "id" TEXT NOT NULL,
    "homeworkId" TEXT NOT NULL,
    "schoolId" TEXT NOT NULL,
    "fileName" TEXT NOT NULL,
    "fileUrl" TEXT NOT NULL,
    "fileSize" INTEGER,
    "mimeType" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "HomeworkAttachment_pkey" PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "HomeworkSubmission" (
    "id" TEXT NOT NULL,
    "homeworkId" TEXT NOT NULL,
    "schoolId" TEXT NOT NULL,
    "studentId" TEXT NOT NULL,
    "status" "HomeworkSubmissionStatus" NOT NULL DEFAULT 'PENDING',
    "comments" TEXT,
    "teacherRemarks" TEXT,
    "marksObtained" DOUBLE PRECISION,
    "percentage" DOUBLE PRECISION,
    "gradeLabel" TEXT,
    "passFail" TEXT,
    "rubricScores" JSONB,
    "submittedAt" TIMESTAMP(3),
    "gradedAt" TIMESTAMP(3),
    "gradedById" TEXT,
    "returnedAt" TIMESTAMP(3),
    "attempt" INTEGER NOT NULL DEFAULT 1,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "HomeworkSubmission_pkey" PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "HomeworkSubmissionFile" (
    "id" TEXT NOT NULL,
    "submissionId" TEXT NOT NULL,
    "schoolId" TEXT NOT NULL,
    "fileName" TEXT NOT NULL,
    "fileUrl" TEXT NOT NULL,
    "fileSize" INTEGER,
    "mimeType" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "HomeworkSubmissionFile_pkey" PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "OnlineClass" (
    "id" TEXT NOT NULL,
    "schoolId" TEXT NOT NULL,
    "title" TEXT NOT NULL,
    "subjectId" TEXT,
    "teacherId" TEXT,
    "classId" TEXT NOT NULL,
    "sectionId" TEXT,
    "provider" "MeetingProvider" NOT NULL DEFAULT 'ZOOM',
    "meetingLink" TEXT,
    "meetingId" TEXT,
    "passcode" TEXT,
    "scheduledDate" TIMESTAMP(3) NOT NULL,
    "startTime" TEXT NOT NULL,
    "endTime" TEXT NOT NULL,
    "startAt" TIMESTAMP(3) NOT NULL,
    "endAt" TIMESTAMP(3) NOT NULL,
    "durationMinutes" INTEGER,
    "description" TEXT,
    "status" "OnlineClassStatus" NOT NULL DEFAULT 'SCHEDULED',
    "recordingUrl" TEXT,
    "recordingDurationSec" INTEGER,
    "recordingSizeBytes" BIGINT,
    "reminderSentAt" TIMESTAMP(3),
    "startedNotifiedAt" TIMESTAMP(3),
    "createdById" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "OnlineClass_pkey" PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "OnlineClassAttendance" (
    "id" TEXT NOT NULL,
    "onlineClassId" TEXT NOT NULL,
    "schoolId" TEXT NOT NULL,
    "studentId" TEXT NOT NULL,
    "status" "OnlineAttendanceStatus" NOT NULL DEFAULT 'PRESENT',
    "source" "OnlineAttendanceSource" NOT NULL DEFAULT 'MANUAL',
    "notes" TEXT,
    "markedById" TEXT,
    "markedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "OnlineClassAttendance_pkey" PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "AcademicCalendarEvent" (
    "id" TEXT NOT NULL,
    "schoolId" TEXT NOT NULL,
    "title" TEXT NOT NULL,
    "description" TEXT,
    "eventType" "CalendarEventType" NOT NULL DEFAULT 'CUSTOM',
    "academicSession" TEXT,
    "classId" TEXT,
    "sectionId" TEXT,
    "teacherId" TEXT,
    "startDate" TIMESTAMP(3) NOT NULL,
    "endDate" TIMESTAMP(3) NOT NULL,
    "startTime" TEXT,
    "endTime" TEXT,
    "allDay" BOOLEAN NOT NULL DEFAULT true,
    "location" TEXT,
    "colorLabel" TEXT,
    "recurrence" "CalendarRecurrence" NOT NULL DEFAULT 'NONE',
    "recurrenceUntil" TIMESTAMP(3),
    "visibility" TEXT NOT NULL DEFAULT 'SCHOOL,TEACHER,STUDENT,PARENT,STAFF',
    "status" "CalendarEventStatus" NOT NULL DEFAULT 'DRAFT',
    "reminderSent7At" TIMESTAMP(3),
    "reminderSent3At" TIMESTAMP(3),
    "reminderSent1At" TIMESTAMP(3),
    "reminderSent0At" TIMESTAMP(3),
    "createdById" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "AcademicCalendarEvent_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX IF NOT EXISTS "School_slug_key" ON "School"("slug");

CREATE UNIQUE INDEX IF NOT EXISTS "School_domain_key" ON "School"("domain");

CREATE UNIQUE INDEX IF NOT EXISTS "SubscriptionPlan_name_key" ON "SubscriptionPlan"("name");

CREATE UNIQUE INDEX IF NOT EXISTS "SchoolSubscription_schoolId_key" ON "SchoolSubscription"("schoolId");

CREATE UNIQUE INDEX IF NOT EXISTS "SaasInvoice_invoiceNo_key" ON "SaasInvoice"("invoiceNo");

CREATE UNIQUE INDEX IF NOT EXISTS "PlatformSetting_key_key" ON "PlatformSetting"("key");

CREATE UNIQUE INDEX IF NOT EXISTS "User_email_key" ON "User"("email");

CREATE UNIQUE INDEX IF NOT EXISTS "User_passwordResetToken_key" ON "User"("passwordResetToken");

CREATE UNIQUE INDEX IF NOT EXISTS "RefreshToken_tokenHash_key" ON "RefreshToken"("tokenHash");

CREATE UNIQUE INDEX IF NOT EXISTS "Class_schoolId_name_key" ON "Class"("schoolId", "name");

CREATE UNIQUE INDEX IF NOT EXISTS "Section_schoolId_classId_name_key" ON "Section"("schoolId", "classId", "name");

CREATE UNIQUE INDEX IF NOT EXISTS "Student_userId_key" ON "Student"("userId");

CREATE UNIQUE INDEX IF NOT EXISTS "Student_schoolId_admissionNo_key" ON "Student"("schoolId", "admissionNo");

CREATE UNIQUE INDEX IF NOT EXISTS "ExamSubject_schoolId_examId_subjectId_key" ON "ExamSubject"("schoolId", "examId", "subjectId");

CREATE UNIQUE INDEX IF NOT EXISTS "Mark_schoolId_examId_subjectId_studentId_key" ON "Mark"("schoolId", "examId", "subjectId", "studentId");

CREATE UNIQUE INDEX IF NOT EXISTS "StudentAttendance_schoolId_studentId_date_key" ON "StudentAttendance"("schoolId", "studentId", "date");

CREATE UNIQUE INDEX IF NOT EXISTS "FeeInvoice_schoolId_invoiceNo_key" ON "FeeInvoice"("schoolId", "invoiceNo");

CREATE UNIQUE INDEX IF NOT EXISTS "FeeInvoice_schoolId_studentId_month_year_key" ON "FeeInvoice"("schoolId", "studentId", "month", "year");

CREATE UNIQUE INDEX IF NOT EXISTS "FeePayment_schoolId_receiptNo_key" ON "FeePayment"("schoolId", "receiptNo");

CREATE UNIQUE INDEX IF NOT EXISTS "Teacher_userId_key" ON "Teacher"("userId");

CREATE UNIQUE INDEX IF NOT EXISTS "Parent_userId_key" ON "Parent"("userId");

CREATE UNIQUE INDEX IF NOT EXISTS "Staff_userId_key" ON "Staff"("userId");

CREATE UNIQUE INDEX IF NOT EXISTS "ExpenseCategory_schoolId_name_key" ON "ExpenseCategory"("schoolId", "name");

CREATE UNIQUE INDEX IF NOT EXISTS "BookCategory_schoolId_name_key" ON "BookCategory"("schoolId", "name");

CREATE UNIQUE INDEX IF NOT EXISTS "Vehicle_schoolId_vehicleNo_key" ON "Vehicle"("schoolId", "vehicleNo");

CREATE UNIQUE INDEX IF NOT EXISTS "TransportRoute_schoolId_name_key" ON "TransportRoute"("schoolId", "name");

CREATE UNIQUE INDEX IF NOT EXISTS "StudentTransport_studentId_key" ON "StudentTransport"("studentId");

CREATE UNIQUE INDEX IF NOT EXISTS "SchoolAuditLog_schoolId_dedupeKey_key" ON "SchoolAuditLog"("schoolId", "dedupeKey");

CREATE UNIQUE INDEX IF NOT EXISTS "UserNotification_userId_dedupeKey_key" ON "UserNotification"("userId", "dedupeKey");

CREATE UNIQUE INDEX IF NOT EXISTS "NotificationPreference_userId_category_key" ON "NotificationPreference"("userId", "category");

CREATE UNIQUE INDEX IF NOT EXISTS "NotificationTemplate_schoolId_code_channel_key" ON "NotificationTemplate"("schoolId", "code", "channel");

CREATE UNIQUE INDEX IF NOT EXISTS "PushDeviceToken_userId_token_key" ON "PushDeviceToken"("userId", "token");

CREATE UNIQUE INDEX IF NOT EXISTS "RolePermission_schoolId_role_key" ON "RolePermission"("schoolId", "role");

CREATE UNIQUE INDEX IF NOT EXISTS "SchoolCustomRole_schoolId_slug_key" ON "SchoolCustomRole"("schoolId", "slug");

CREATE UNIQUE INDEX IF NOT EXISTS "HomeworkSubmission_homeworkId_studentId_attempt_key" ON "HomeworkSubmission"("homeworkId", "studentId", "attempt");

CREATE UNIQUE INDEX IF NOT EXISTS "OnlineClassAttendance_onlineClassId_studentId_key" ON "OnlineClassAttendance"("onlineClassId", "studentId");

CREATE INDEX IF NOT EXISTS "SchoolSubscription_planId_idx" ON "SchoolSubscription"("planId");

CREATE INDEX IF NOT EXISTS "SchoolSubscription_status_idx" ON "SchoolSubscription"("status");

CREATE INDEX IF NOT EXISTS "SaasInvoice_schoolId_idx" ON "SaasInvoice"("schoolId");

CREATE INDEX IF NOT EXISTS "SaasInvoice_status_idx" ON "SaasInvoice"("status");

CREATE INDEX IF NOT EXISTS "AuditLog_schoolId_idx" ON "AuditLog"("schoolId");

CREATE INDEX IF NOT EXISTS "AuditLog_actorId_idx" ON "AuditLog"("actorId");

CREATE INDEX IF NOT EXISTS "AuditLog_createdAt_idx" ON "AuditLog"("createdAt");

CREATE INDEX IF NOT EXISTS "User_schoolId_idx" ON "User"("schoolId");

CREATE INDEX IF NOT EXISTS "User_email_idx" ON "User"("email");

CREATE INDEX IF NOT EXISTS "User_passwordResetToken_idx" ON "User"("passwordResetToken");

CREATE INDEX IF NOT EXISTS "User_customRoleId_idx" ON "User"("customRoleId");

CREATE INDEX IF NOT EXISTS "RefreshToken_userId_idx" ON "RefreshToken"("userId");

CREATE INDEX IF NOT EXISTS "RefreshToken_expiresAt_idx" ON "RefreshToken"("expiresAt");

CREATE INDEX IF NOT EXISTS "LoginOtpChallenge_userId_createdAt_idx" ON "LoginOtpChallenge"("userId", "createdAt");

CREATE INDEX IF NOT EXISTS "LoginOtpChallenge_ipAddress_createdAt_idx" ON "LoginOtpChallenge"("ipAddress", "createdAt");

CREATE INDEX IF NOT EXISTS "LoginOtpChallenge_expiresAt_idx" ON "LoginOtpChallenge"("expiresAt");

CREATE INDEX IF NOT EXISTS "LoginOtpChallenge_userId_purpose_usedAt_idx" ON "LoginOtpChallenge"("userId", "purpose", "usedAt");

CREATE INDEX IF NOT EXISTS "Class_schoolId_idx" ON "Class"("schoolId");

CREATE INDEX IF NOT EXISTS "Class_classTeacherId_idx" ON "Class"("classTeacherId");

CREATE INDEX IF NOT EXISTS "Section_schoolId_idx" ON "Section"("schoolId");

CREATE INDEX IF NOT EXISTS "Section_classId_idx" ON "Section"("classId");

CREATE INDEX IF NOT EXISTS "Section_teacherId_idx" ON "Section"("teacherId");

CREATE INDEX IF NOT EXISTS "Subject_schoolId_idx" ON "Subject"("schoolId");

CREATE INDEX IF NOT EXISTS "Subject_sectionId_idx" ON "Subject"("sectionId");

CREATE INDEX IF NOT EXISTS "Subject_teacherId_idx" ON "Subject"("teacherId");

CREATE INDEX IF NOT EXISTS "Student_schoolId_idx" ON "Student"("schoolId");

CREATE INDEX IF NOT EXISTS "Student_classId_idx" ON "Student"("classId");

CREATE INDEX IF NOT EXISTS "Student_sectionId_idx" ON "Student"("sectionId");

CREATE INDEX IF NOT EXISTS "Student_status_idx" ON "Student"("status");

CREATE INDEX IF NOT EXISTS "Student_schoolId_status_idx" ON "Student"("schoolId", "status");

CREATE INDEX IF NOT EXISTS "Student_schoolId_classId_sectionId_idx" ON "Student"("schoolId", "classId", "sectionId");

CREATE INDEX IF NOT EXISTS "Exam_schoolId_idx" ON "Exam"("schoolId");

CREATE INDEX IF NOT EXISTS "Exam_classId_idx" ON "Exam"("classId");

CREATE INDEX IF NOT EXISTS "Exam_sectionId_idx" ON "Exam"("sectionId");

CREATE INDEX IF NOT EXISTS "Exam_schoolId_status_idx" ON "Exam"("schoolId", "status");

CREATE INDEX IF NOT EXISTS "Exam_startDate_idx" ON "Exam"("startDate");

CREATE INDEX IF NOT EXISTS "ExamSubject_schoolId_idx" ON "ExamSubject"("schoolId");

CREATE INDEX IF NOT EXISTS "ExamSubject_examId_idx" ON "ExamSubject"("examId");

CREATE INDEX IF NOT EXISTS "ExamSubject_subjectId_idx" ON "ExamSubject"("subjectId");

CREATE INDEX IF NOT EXISTS "Mark_schoolId_idx" ON "Mark"("schoolId");

CREATE INDEX IF NOT EXISTS "Mark_examId_idx" ON "Mark"("examId");

CREATE INDEX IF NOT EXISTS "Mark_studentId_idx" ON "Mark"("studentId");

CREATE INDEX IF NOT EXISTS "Mark_subjectId_idx" ON "Mark"("subjectId");

CREATE INDEX IF NOT EXISTS "Mark_schoolId_examId_idx" ON "Mark"("schoolId", "examId");

CREATE INDEX IF NOT EXISTS "Grade_schoolId_idx" ON "Grade"("schoolId");

CREATE INDEX IF NOT EXISTS "StudentAttendance_schoolId_idx" ON "StudentAttendance"("schoolId");

CREATE INDEX IF NOT EXISTS "StudentAttendance_studentId_idx" ON "StudentAttendance"("studentId");

CREATE INDEX IF NOT EXISTS "StudentAttendance_classId_idx" ON "StudentAttendance"("classId");

CREATE INDEX IF NOT EXISTS "StudentAttendance_sectionId_idx" ON "StudentAttendance"("sectionId");

CREATE INDEX IF NOT EXISTS "StudentAttendance_date_idx" ON "StudentAttendance"("date");

CREATE INDEX IF NOT EXISTS "StudentAttendance_schoolId_date_idx" ON "StudentAttendance"("schoolId", "date");

CREATE INDEX IF NOT EXISTS "StudentAttendance_schoolId_classId_date_idx" ON "StudentAttendance"("schoolId", "classId", "date");

CREATE INDEX IF NOT EXISTS "FeeStructure_schoolId_idx" ON "FeeStructure"("schoolId");

CREATE INDEX IF NOT EXISTS "FeeStructure_classId_idx" ON "FeeStructure"("classId");

CREATE INDEX IF NOT EXISTS "FeeInvoice_schoolId_idx" ON "FeeInvoice"("schoolId");

CREATE INDEX IF NOT EXISTS "FeeInvoice_studentId_idx" ON "FeeInvoice"("studentId");

CREATE INDEX IF NOT EXISTS "FeeInvoice_status_idx" ON "FeeInvoice"("status");

CREATE INDEX IF NOT EXISTS "FeeInvoice_schoolId_month_year_idx" ON "FeeInvoice"("schoolId", "month", "year");

CREATE INDEX IF NOT EXISTS "FeeInvoice_schoolId_status_idx" ON "FeeInvoice"("schoolId", "status");

CREATE INDEX IF NOT EXISTS "FeePayment_schoolId_idx" ON "FeePayment"("schoolId");

CREATE INDEX IF NOT EXISTS "FeePayment_invoiceId_idx" ON "FeePayment"("invoiceId");

CREATE INDEX IF NOT EXISTS "FeePayment_paymentDate_idx" ON "FeePayment"("paymentDate");

CREATE INDEX IF NOT EXISTS "FeePayment_schoolId_paymentDate_idx" ON "FeePayment"("schoolId", "paymentDate");

CREATE INDEX IF NOT EXISTS "Teacher_schoolId_idx" ON "Teacher"("schoolId");

CREATE INDEX IF NOT EXISTS "Teacher_schoolId_status_idx" ON "Teacher"("schoolId", "status");

CREATE INDEX IF NOT EXISTS "Parent_schoolId_idx" ON "Parent"("schoolId");

CREATE INDEX IF NOT EXISTS "Parent_studentId_idx" ON "Parent"("studentId");

CREATE INDEX IF NOT EXISTS "Parent_schoolId_status_idx" ON "Parent"("schoolId", "status");

CREATE INDEX IF NOT EXISTS "Staff_schoolId_idx" ON "Staff"("schoolId");

CREATE INDEX IF NOT EXISTS "Staff_schoolId_status_idx" ON "Staff"("schoolId", "status");

CREATE INDEX IF NOT EXISTS "ExpenseCategory_schoolId_idx" ON "ExpenseCategory"("schoolId");

CREATE INDEX IF NOT EXISTS "Expense_schoolId_idx" ON "Expense"("schoolId");

CREATE INDEX IF NOT EXISTS "Expense_categoryId_idx" ON "Expense"("categoryId");

CREATE INDEX IF NOT EXISTS "Expense_date_idx" ON "Expense"("date");

CREATE INDEX IF NOT EXISTS "Expense_schoolId_date_idx" ON "Expense"("schoolId", "date");

CREATE INDEX IF NOT EXISTS "Expense_schoolId_status_idx" ON "Expense"("schoolId", "status");

CREATE INDEX IF NOT EXISTS "Payroll_schoolId_idx" ON "Payroll"("schoolId");

CREATE INDEX IF NOT EXISTS "Payroll_teacherId_idx" ON "Payroll"("teacherId");

CREATE INDEX IF NOT EXISTS "Payroll_staffId_idx" ON "Payroll"("staffId");

CREATE INDEX IF NOT EXISTS "Payroll_month_year_idx" ON "Payroll"("month", "year");

CREATE INDEX IF NOT EXISTS "Payroll_status_idx" ON "Payroll"("status");

CREATE INDEX IF NOT EXISTS "Payroll_schoolId_month_year_idx" ON "Payroll"("schoolId", "month", "year");

CREATE INDEX IF NOT EXISTS "Payroll_schoolId_status_idx" ON "Payroll"("schoolId", "status");

CREATE INDEX IF NOT EXISTS "TimetableEntry_schoolId_idx" ON "TimetableEntry"("schoolId");

CREATE INDEX IF NOT EXISTS "TimetableEntry_classId_idx" ON "TimetableEntry"("classId");

CREATE INDEX IF NOT EXISTS "TimetableEntry_sectionId_idx" ON "TimetableEntry"("sectionId");

CREATE INDEX IF NOT EXISTS "TimetableEntry_teacherId_idx" ON "TimetableEntry"("teacherId");

CREATE INDEX IF NOT EXISTS "TimetableEntry_dayOfWeek_idx" ON "TimetableEntry"("dayOfWeek");

CREATE INDEX IF NOT EXISTS "BookCategory_schoolId_idx" ON "BookCategory"("schoolId");

CREATE INDEX IF NOT EXISTS "Book_schoolId_idx" ON "Book"("schoolId");

CREATE INDEX IF NOT EXISTS "Book_categoryId_idx" ON "Book"("categoryId");

CREATE INDEX IF NOT EXISTS "Book_schoolId_status_idx" ON "Book"("schoolId", "status");

CREATE INDEX IF NOT EXISTS "BookIssue_schoolId_idx" ON "BookIssue"("schoolId");

CREATE INDEX IF NOT EXISTS "BookIssue_bookId_idx" ON "BookIssue"("bookId");

CREATE INDEX IF NOT EXISTS "BookIssue_studentId_idx" ON "BookIssue"("studentId");

CREATE INDEX IF NOT EXISTS "BookIssue_status_idx" ON "BookIssue"("status");

CREATE INDEX IF NOT EXISTS "BookIssue_dueDate_idx" ON "BookIssue"("dueDate");

CREATE INDEX IF NOT EXISTS "BookIssue_schoolId_status_idx" ON "BookIssue"("schoolId", "status");

CREATE INDEX IF NOT EXISTS "Vehicle_schoolId_idx" ON "Vehicle"("schoolId");

CREATE INDEX IF NOT EXISTS "TransportRoute_schoolId_idx" ON "TransportRoute"("schoolId");

CREATE INDEX IF NOT EXISTS "StudentTransport_schoolId_idx" ON "StudentTransport"("schoolId");

CREATE INDEX IF NOT EXISTS "StudentTransport_routeId_idx" ON "StudentTransport"("routeId");

CREATE INDEX IF NOT EXISTS "Notice_schoolId_idx" ON "Notice"("schoolId");

CREATE INDEX IF NOT EXISTS "Notice_createdById_idx" ON "Notice"("createdById");

CREATE INDEX IF NOT EXISTS "Notice_type_idx" ON "Notice"("type");

CREATE INDEX IF NOT EXISTS "Notice_schoolId_isPublished_idx" ON "Notice"("schoolId", "isPublished");

CREATE INDEX IF NOT EXISTS "StudentDocument_schoolId_idx" ON "StudentDocument"("schoolId");

CREATE INDEX IF NOT EXISTS "StudentDocument_studentId_idx" ON "StudentDocument"("studentId");

CREATE INDEX IF NOT EXISTS "StudentDocument_fileUrl_idx" ON "StudentDocument"("fileUrl");

CREATE INDEX IF NOT EXISTS "SchoolAuditLog_schoolId_idx" ON "SchoolAuditLog"("schoolId");

CREATE INDEX IF NOT EXISTS "SchoolAuditLog_userId_idx" ON "SchoolAuditLog"("userId");

CREATE INDEX IF NOT EXISTS "SchoolAuditLog_createdAt_idx" ON "SchoolAuditLog"("createdAt");

CREATE INDEX IF NOT EXISTS "SchoolAuditLog_action_idx" ON "SchoolAuditLog"("action");

CREATE INDEX IF NOT EXISTS "SchoolAuditLog_entity_entityId_idx" ON "SchoolAuditLog"("entity", "entityId");

CREATE INDEX IF NOT EXISTS "NotificationLog_schoolId_idx" ON "NotificationLog"("schoolId");

CREATE INDEX IF NOT EXISTS "NotificationLog_status_idx" ON "NotificationLog"("status");

CREATE INDEX IF NOT EXISTS "NotificationLog_channel_idx" ON "NotificationLog"("channel");

CREATE INDEX IF NOT EXISTS "NotificationLog_eventType_idx" ON "NotificationLog"("eventType");

CREATE INDEX IF NOT EXISTS "NotificationLog_campaignId_idx" ON "NotificationLog"("campaignId");

CREATE INDEX IF NOT EXISTS "NotificationLog_senderId_idx" ON "NotificationLog"("senderId");

CREATE INDEX IF NOT EXISTS "NotificationLog_createdAt_idx" ON "NotificationLog"("createdAt");

CREATE INDEX IF NOT EXISTS "UserNotification_userId_isRead_idx" ON "UserNotification"("userId", "isRead");

CREATE INDEX IF NOT EXISTS "UserNotification_userId_category_idx" ON "UserNotification"("userId", "category");

CREATE INDEX IF NOT EXISTS "UserNotification_userId_isArchived_idx" ON "UserNotification"("userId", "isArchived");

CREATE INDEX IF NOT EXISTS "UserNotification_schoolId_idx" ON "UserNotification"("schoolId");

CREATE INDEX IF NOT EXISTS "UserNotification_createdAt_idx" ON "UserNotification"("createdAt");

CREATE INDEX IF NOT EXISTS "NotificationPreference_userId_idx" ON "NotificationPreference"("userId");

CREATE INDEX IF NOT EXISTS "NotificationTemplate_schoolId_idx" ON "NotificationTemplate"("schoolId");

CREATE INDEX IF NOT EXISTS "NotificationTemplate_code_idx" ON "NotificationTemplate"("code");

CREATE INDEX IF NOT EXISTS "NotificationTemplate_category_idx" ON "NotificationTemplate"("category");

CREATE INDEX IF NOT EXISTS "NotificationCampaign_schoolId_idx" ON "NotificationCampaign"("schoolId");

CREATE INDEX IF NOT EXISTS "NotificationCampaign_status_idx" ON "NotificationCampaign"("status");

CREATE INDEX IF NOT EXISTS "NotificationCampaign_scheduledAt_idx" ON "NotificationCampaign"("scheduledAt");

CREATE INDEX IF NOT EXISTS "NotificationCampaign_nextRunAt_idx" ON "NotificationCampaign"("nextRunAt");

CREATE INDEX IF NOT EXISTS "NotificationCampaign_createdById_idx" ON "NotificationCampaign"("createdById");

CREATE INDEX IF NOT EXISTS "PushDeviceToken_userId_idx" ON "PushDeviceToken"("userId");

CREATE INDEX IF NOT EXISTS "PushDeviceToken_isActive_idx" ON "PushDeviceToken"("isActive");

CREATE INDEX IF NOT EXISTS "RolePermission_schoolId_idx" ON "RolePermission"("schoolId");

CREATE INDEX IF NOT EXISTS "SchoolCustomRole_schoolId_idx" ON "SchoolCustomRole"("schoolId");

CREATE INDEX IF NOT EXISTS "Homework_schoolId_idx" ON "Homework"("schoolId");

CREATE INDEX IF NOT EXISTS "Homework_classId_idx" ON "Homework"("classId");

CREATE INDEX IF NOT EXISTS "Homework_sectionId_idx" ON "Homework"("sectionId");

CREATE INDEX IF NOT EXISTS "Homework_subjectId_idx" ON "Homework"("subjectId");

CREATE INDEX IF NOT EXISTS "Homework_teacherId_idx" ON "Homework"("teacherId");

CREATE INDEX IF NOT EXISTS "Homework_dueDate_idx" ON "Homework"("dueDate");

CREATE INDEX IF NOT EXISTS "Homework_status_idx" ON "Homework"("status");

CREATE INDEX IF NOT EXISTS "Homework_schoolId_status_idx" ON "Homework"("schoolId", "status");

CREATE INDEX IF NOT EXISTS "Homework_schoolId_dueDate_idx" ON "Homework"("schoolId", "dueDate");

CREATE INDEX IF NOT EXISTS "Homework_onlineClassId_idx" ON "Homework"("onlineClassId");

CREATE INDEX IF NOT EXISTS "HomeworkAttachment_homeworkId_idx" ON "HomeworkAttachment"("homeworkId");

CREATE INDEX IF NOT EXISTS "HomeworkAttachment_schoolId_idx" ON "HomeworkAttachment"("schoolId");

CREATE INDEX IF NOT EXISTS "HomeworkSubmission_homeworkId_idx" ON "HomeworkSubmission"("homeworkId");

CREATE INDEX IF NOT EXISTS "HomeworkSubmission_studentId_idx" ON "HomeworkSubmission"("studentId");

CREATE INDEX IF NOT EXISTS "HomeworkSubmission_schoolId_idx" ON "HomeworkSubmission"("schoolId");

CREATE INDEX IF NOT EXISTS "HomeworkSubmission_status_idx" ON "HomeworkSubmission"("status");

CREATE INDEX IF NOT EXISTS "HomeworkSubmission_schoolId_status_idx" ON "HomeworkSubmission"("schoolId", "status");

CREATE INDEX IF NOT EXISTS "HomeworkSubmissionFile_submissionId_idx" ON "HomeworkSubmissionFile"("submissionId");

CREATE INDEX IF NOT EXISTS "HomeworkSubmissionFile_schoolId_idx" ON "HomeworkSubmissionFile"("schoolId");

CREATE INDEX IF NOT EXISTS "OnlineClass_schoolId_idx" ON "OnlineClass"("schoolId");

CREATE INDEX IF NOT EXISTS "OnlineClass_classId_idx" ON "OnlineClass"("classId");

CREATE INDEX IF NOT EXISTS "OnlineClass_sectionId_idx" ON "OnlineClass"("sectionId");

CREATE INDEX IF NOT EXISTS "OnlineClass_subjectId_idx" ON "OnlineClass"("subjectId");

CREATE INDEX IF NOT EXISTS "OnlineClass_teacherId_idx" ON "OnlineClass"("teacherId");

CREATE INDEX IF NOT EXISTS "OnlineClass_startAt_idx" ON "OnlineClass"("startAt");

CREATE INDEX IF NOT EXISTS "OnlineClass_status_idx" ON "OnlineClass"("status");

CREATE INDEX IF NOT EXISTS "OnlineClass_schoolId_status_idx" ON "OnlineClass"("schoolId", "status");

CREATE INDEX IF NOT EXISTS "OnlineClass_schoolId_startAt_idx" ON "OnlineClass"("schoolId", "startAt");

CREATE INDEX IF NOT EXISTS "OnlineClass_provider_idx" ON "OnlineClass"("provider");

CREATE INDEX IF NOT EXISTS "OnlineClassAttendance_onlineClassId_idx" ON "OnlineClassAttendance"("onlineClassId");

CREATE INDEX IF NOT EXISTS "OnlineClassAttendance_studentId_idx" ON "OnlineClassAttendance"("studentId");

CREATE INDEX IF NOT EXISTS "OnlineClassAttendance_schoolId_idx" ON "OnlineClassAttendance"("schoolId");

CREATE INDEX IF NOT EXISTS "OnlineClassAttendance_status_idx" ON "OnlineClassAttendance"("status");

CREATE INDEX IF NOT EXISTS "OnlineClassAttendance_schoolId_status_idx" ON "OnlineClassAttendance"("schoolId", "status");

CREATE INDEX IF NOT EXISTS "AcademicCalendarEvent_schoolId_idx" ON "AcademicCalendarEvent"("schoolId");

CREATE INDEX IF NOT EXISTS "AcademicCalendarEvent_classId_idx" ON "AcademicCalendarEvent"("classId");

CREATE INDEX IF NOT EXISTS "AcademicCalendarEvent_sectionId_idx" ON "AcademicCalendarEvent"("sectionId");

CREATE INDEX IF NOT EXISTS "AcademicCalendarEvent_teacherId_idx" ON "AcademicCalendarEvent"("teacherId");

CREATE INDEX IF NOT EXISTS "AcademicCalendarEvent_eventType_idx" ON "AcademicCalendarEvent"("eventType");

CREATE INDEX IF NOT EXISTS "AcademicCalendarEvent_status_idx" ON "AcademicCalendarEvent"("status");

CREATE INDEX IF NOT EXISTS "AcademicCalendarEvent_startDate_idx" ON "AcademicCalendarEvent"("startDate");

CREATE INDEX IF NOT EXISTS "AcademicCalendarEvent_endDate_idx" ON "AcademicCalendarEvent"("endDate");

CREATE INDEX IF NOT EXISTS "AcademicCalendarEvent_schoolId_status_idx" ON "AcademicCalendarEvent"("schoolId", "status");

CREATE INDEX IF NOT EXISTS "AcademicCalendarEvent_schoolId_startDate_idx" ON "AcademicCalendarEvent"("schoolId", "startDate");

CREATE INDEX IF NOT EXISTS "AcademicCalendarEvent_schoolId_endDate_idx" ON "AcademicCalendarEvent"("schoolId", "endDate");

DO $$ BEGIN
  ALTER TABLE "SchoolSubscription" ADD CONSTRAINT "SchoolSubscription_schoolId_fkey" FOREIGN KEY ("schoolId") REFERENCES "School"("id") ON DELETE CASCADE ON UPDATE CASCADE;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "SchoolSubscription" ADD CONSTRAINT "SchoolSubscription_planId_fkey" FOREIGN KEY ("planId") REFERENCES "SubscriptionPlan"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "SaasInvoice" ADD CONSTRAINT "SaasInvoice_schoolId_fkey" FOREIGN KEY ("schoolId") REFERENCES "School"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "SaasInvoice" ADD CONSTRAINT "SaasInvoice_subscriptionId_fkey" FOREIGN KEY ("subscriptionId") REFERENCES "SchoolSubscription"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "User" ADD CONSTRAINT "User_schoolId_fkey" FOREIGN KEY ("schoolId") REFERENCES "School"("id") ON DELETE SET NULL ON UPDATE CASCADE;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "User" ADD CONSTRAINT "User_customRoleId_fkey" FOREIGN KEY ("customRoleId") REFERENCES "SchoolCustomRole"("id") ON DELETE SET NULL ON UPDATE CASCADE;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "RefreshToken" ADD CONSTRAINT "RefreshToken_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "LoginOtpChallenge" ADD CONSTRAINT "LoginOtpChallenge_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "Class" ADD CONSTRAINT "Class_schoolId_fkey" FOREIGN KEY ("schoolId") REFERENCES "School"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "Class" ADD CONSTRAINT "Class_classTeacherId_fkey" FOREIGN KEY ("classTeacherId") REFERENCES "Teacher"("id") ON DELETE SET NULL ON UPDATE CASCADE;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "Section" ADD CONSTRAINT "Section_schoolId_fkey" FOREIGN KEY ("schoolId") REFERENCES "School"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "Section" ADD CONSTRAINT "Section_classId_fkey" FOREIGN KEY ("classId") REFERENCES "Class"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "Section" ADD CONSTRAINT "Section_teacherId_fkey" FOREIGN KEY ("teacherId") REFERENCES "Teacher"("id") ON DELETE SET NULL ON UPDATE CASCADE;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "Subject" ADD CONSTRAINT "Subject_schoolId_fkey" FOREIGN KEY ("schoolId") REFERENCES "School"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "Subject" ADD CONSTRAINT "Subject_classId_fkey" FOREIGN KEY ("classId") REFERENCES "Class"("id") ON DELETE SET NULL ON UPDATE CASCADE;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "Subject" ADD CONSTRAINT "Subject_sectionId_fkey" FOREIGN KEY ("sectionId") REFERENCES "Section"("id") ON DELETE SET NULL ON UPDATE CASCADE;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "Subject" ADD CONSTRAINT "Subject_teacherId_fkey" FOREIGN KEY ("teacherId") REFERENCES "Teacher"("id") ON DELETE SET NULL ON UPDATE CASCADE;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "Student" ADD CONSTRAINT "Student_schoolId_fkey" FOREIGN KEY ("schoolId") REFERENCES "School"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "Student" ADD CONSTRAINT "Student_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "Student" ADD CONSTRAINT "Student_classId_fkey" FOREIGN KEY ("classId") REFERENCES "Class"("id") ON DELETE SET NULL ON UPDATE CASCADE;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "Student" ADD CONSTRAINT "Student_sectionId_fkey" FOREIGN KEY ("sectionId") REFERENCES "Section"("id") ON DELETE SET NULL ON UPDATE CASCADE;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "Exam" ADD CONSTRAINT "Exam_schoolId_fkey" FOREIGN KEY ("schoolId") REFERENCES "School"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "Exam" ADD CONSTRAINT "Exam_classId_fkey" FOREIGN KEY ("classId") REFERENCES "Class"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "Exam" ADD CONSTRAINT "Exam_sectionId_fkey" FOREIGN KEY ("sectionId") REFERENCES "Section"("id") ON DELETE SET NULL ON UPDATE CASCADE;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "ExamSubject" ADD CONSTRAINT "ExamSubject_schoolId_fkey" FOREIGN KEY ("schoolId") REFERENCES "School"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "ExamSubject" ADD CONSTRAINT "ExamSubject_examId_fkey" FOREIGN KEY ("examId") REFERENCES "Exam"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "ExamSubject" ADD CONSTRAINT "ExamSubject_subjectId_fkey" FOREIGN KEY ("subjectId") REFERENCES "Subject"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "Mark" ADD CONSTRAINT "Mark_schoolId_fkey" FOREIGN KEY ("schoolId") REFERENCES "School"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "Mark" ADD CONSTRAINT "Mark_examId_fkey" FOREIGN KEY ("examId") REFERENCES "Exam"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "Mark" ADD CONSTRAINT "Mark_subjectId_fkey" FOREIGN KEY ("subjectId") REFERENCES "Subject"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "Mark" ADD CONSTRAINT "Mark_studentId_fkey" FOREIGN KEY ("studentId") REFERENCES "Student"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "Grade" ADD CONSTRAINT "Grade_schoolId_fkey" FOREIGN KEY ("schoolId") REFERENCES "School"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "StudentAttendance" ADD CONSTRAINT "StudentAttendance_schoolId_fkey" FOREIGN KEY ("schoolId") REFERENCES "School"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "StudentAttendance" ADD CONSTRAINT "StudentAttendance_studentId_fkey" FOREIGN KEY ("studentId") REFERENCES "Student"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "StudentAttendance" ADD CONSTRAINT "StudentAttendance_classId_fkey" FOREIGN KEY ("classId") REFERENCES "Class"("id") ON DELETE SET NULL ON UPDATE CASCADE;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "StudentAttendance" ADD CONSTRAINT "StudentAttendance_sectionId_fkey" FOREIGN KEY ("sectionId") REFERENCES "Section"("id") ON DELETE SET NULL ON UPDATE CASCADE;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "StudentAttendance" ADD CONSTRAINT "StudentAttendance_markedById_fkey" FOREIGN KEY ("markedById") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "FeeStructure" ADD CONSTRAINT "FeeStructure_schoolId_fkey" FOREIGN KEY ("schoolId") REFERENCES "School"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "FeeStructure" ADD CONSTRAINT "FeeStructure_classId_fkey" FOREIGN KEY ("classId") REFERENCES "Class"("id") ON DELETE SET NULL ON UPDATE CASCADE;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "FeeInvoice" ADD CONSTRAINT "FeeInvoice_schoolId_fkey" FOREIGN KEY ("schoolId") REFERENCES "School"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "FeeInvoice" ADD CONSTRAINT "FeeInvoice_studentId_fkey" FOREIGN KEY ("studentId") REFERENCES "Student"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "FeePayment" ADD CONSTRAINT "FeePayment_schoolId_fkey" FOREIGN KEY ("schoolId") REFERENCES "School"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "FeePayment" ADD CONSTRAINT "FeePayment_invoiceId_fkey" FOREIGN KEY ("invoiceId") REFERENCES "FeeInvoice"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "Teacher" ADD CONSTRAINT "Teacher_schoolId_fkey" FOREIGN KEY ("schoolId") REFERENCES "School"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "Teacher" ADD CONSTRAINT "Teacher_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "Parent" ADD CONSTRAINT "Parent_schoolId_fkey" FOREIGN KEY ("schoolId") REFERENCES "School"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "Parent" ADD CONSTRAINT "Parent_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "Parent" ADD CONSTRAINT "Parent_studentId_fkey" FOREIGN KEY ("studentId") REFERENCES "Student"("id") ON DELETE SET NULL ON UPDATE CASCADE;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "Staff" ADD CONSTRAINT "Staff_schoolId_fkey" FOREIGN KEY ("schoolId") REFERENCES "School"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "Staff" ADD CONSTRAINT "Staff_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "ExpenseCategory" ADD CONSTRAINT "ExpenseCategory_schoolId_fkey" FOREIGN KEY ("schoolId") REFERENCES "School"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "Expense" ADD CONSTRAINT "Expense_schoolId_fkey" FOREIGN KEY ("schoolId") REFERENCES "School"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "Expense" ADD CONSTRAINT "Expense_categoryId_fkey" FOREIGN KEY ("categoryId") REFERENCES "ExpenseCategory"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "Payroll" ADD CONSTRAINT "Payroll_schoolId_fkey" FOREIGN KEY ("schoolId") REFERENCES "School"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "Payroll" ADD CONSTRAINT "Payroll_teacherId_fkey" FOREIGN KEY ("teacherId") REFERENCES "Teacher"("id") ON DELETE SET NULL ON UPDATE CASCADE;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "Payroll" ADD CONSTRAINT "Payroll_staffId_fkey" FOREIGN KEY ("staffId") REFERENCES "Staff"("id") ON DELETE SET NULL ON UPDATE CASCADE;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "Payroll" ADD CONSTRAINT "Payroll_paidById_fkey" FOREIGN KEY ("paidById") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "TimetableEntry" ADD CONSTRAINT "TimetableEntry_schoolId_fkey" FOREIGN KEY ("schoolId") REFERENCES "School"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "TimetableEntry" ADD CONSTRAINT "TimetableEntry_classId_fkey" FOREIGN KEY ("classId") REFERENCES "Class"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "TimetableEntry" ADD CONSTRAINT "TimetableEntry_sectionId_fkey" FOREIGN KEY ("sectionId") REFERENCES "Section"("id") ON DELETE SET NULL ON UPDATE CASCADE;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "TimetableEntry" ADD CONSTRAINT "TimetableEntry_subjectId_fkey" FOREIGN KEY ("subjectId") REFERENCES "Subject"("id") ON DELETE SET NULL ON UPDATE CASCADE;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "TimetableEntry" ADD CONSTRAINT "TimetableEntry_teacherId_fkey" FOREIGN KEY ("teacherId") REFERENCES "Teacher"("id") ON DELETE SET NULL ON UPDATE CASCADE;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "BookCategory" ADD CONSTRAINT "BookCategory_schoolId_fkey" FOREIGN KEY ("schoolId") REFERENCES "School"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "Book" ADD CONSTRAINT "Book_schoolId_fkey" FOREIGN KEY ("schoolId") REFERENCES "School"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "Book" ADD CONSTRAINT "Book_categoryId_fkey" FOREIGN KEY ("categoryId") REFERENCES "BookCategory"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "BookIssue" ADD CONSTRAINT "BookIssue_schoolId_fkey" FOREIGN KEY ("schoolId") REFERENCES "School"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "BookIssue" ADD CONSTRAINT "BookIssue_bookId_fkey" FOREIGN KEY ("bookId") REFERENCES "Book"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "BookIssue" ADD CONSTRAINT "BookIssue_studentId_fkey" FOREIGN KEY ("studentId") REFERENCES "Student"("id") ON DELETE SET NULL ON UPDATE CASCADE;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "BookIssue" ADD CONSTRAINT "BookIssue_issuedById_fkey" FOREIGN KEY ("issuedById") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "Vehicle" ADD CONSTRAINT "Vehicle_schoolId_fkey" FOREIGN KEY ("schoolId") REFERENCES "School"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "TransportRoute" ADD CONSTRAINT "TransportRoute_schoolId_fkey" FOREIGN KEY ("schoolId") REFERENCES "School"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "TransportRoute" ADD CONSTRAINT "TransportRoute_vehicleId_fkey" FOREIGN KEY ("vehicleId") REFERENCES "Vehicle"("id") ON DELETE SET NULL ON UPDATE CASCADE;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "StudentTransport" ADD CONSTRAINT "StudentTransport_schoolId_fkey" FOREIGN KEY ("schoolId") REFERENCES "School"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "StudentTransport" ADD CONSTRAINT "StudentTransport_studentId_fkey" FOREIGN KEY ("studentId") REFERENCES "Student"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "StudentTransport" ADD CONSTRAINT "StudentTransport_routeId_fkey" FOREIGN KEY ("routeId") REFERENCES "TransportRoute"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "Notice" ADD CONSTRAINT "Notice_schoolId_fkey" FOREIGN KEY ("schoolId") REFERENCES "School"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "Notice" ADD CONSTRAINT "Notice_createdById_fkey" FOREIGN KEY ("createdById") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "StudentDocument" ADD CONSTRAINT "StudentDocument_schoolId_fkey" FOREIGN KEY ("schoolId") REFERENCES "School"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "StudentDocument" ADD CONSTRAINT "StudentDocument_studentId_fkey" FOREIGN KEY ("studentId") REFERENCES "Student"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "StudentDocument" ADD CONSTRAINT "StudentDocument_uploadedById_fkey" FOREIGN KEY ("uploadedById") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "SchoolAuditLog" ADD CONSTRAINT "SchoolAuditLog_schoolId_fkey" FOREIGN KEY ("schoolId") REFERENCES "School"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "SchoolAuditLog" ADD CONSTRAINT "SchoolAuditLog_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "NotificationLog" ADD CONSTRAINT "NotificationLog_campaignId_fkey" FOREIGN KEY ("campaignId") REFERENCES "NotificationCampaign"("id") ON DELETE SET NULL ON UPDATE CASCADE;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "NotificationLog" ADD CONSTRAINT "NotificationLog_templateId_fkey" FOREIGN KEY ("templateId") REFERENCES "NotificationTemplate"("id") ON DELETE SET NULL ON UPDATE CASCADE;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "UserNotification" ADD CONSTRAINT "UserNotification_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "UserNotification" ADD CONSTRAINT "UserNotification_schoolId_fkey" FOREIGN KEY ("schoolId") REFERENCES "School"("id") ON DELETE SET NULL ON UPDATE CASCADE;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "NotificationPreference" ADD CONSTRAINT "NotificationPreference_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "NotificationTemplate" ADD CONSTRAINT "NotificationTemplate_schoolId_fkey" FOREIGN KEY ("schoolId") REFERENCES "School"("id") ON DELETE CASCADE ON UPDATE CASCADE;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "NotificationCampaign" ADD CONSTRAINT "NotificationCampaign_schoolId_fkey" FOREIGN KEY ("schoolId") REFERENCES "School"("id") ON DELETE CASCADE ON UPDATE CASCADE;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "PushDeviceToken" ADD CONSTRAINT "PushDeviceToken_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "RolePermission" ADD CONSTRAINT "RolePermission_schoolId_fkey" FOREIGN KEY ("schoolId") REFERENCES "School"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "SchoolCustomRole" ADD CONSTRAINT "SchoolCustomRole_schoolId_fkey" FOREIGN KEY ("schoolId") REFERENCES "School"("id") ON DELETE CASCADE ON UPDATE CASCADE;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "Homework" ADD CONSTRAINT "Homework_schoolId_fkey" FOREIGN KEY ("schoolId") REFERENCES "School"("id") ON DELETE CASCADE ON UPDATE CASCADE;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "Homework" ADD CONSTRAINT "Homework_subjectId_fkey" FOREIGN KEY ("subjectId") REFERENCES "Subject"("id") ON DELETE SET NULL ON UPDATE CASCADE;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "Homework" ADD CONSTRAINT "Homework_classId_fkey" FOREIGN KEY ("classId") REFERENCES "Class"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "Homework" ADD CONSTRAINT "Homework_sectionId_fkey" FOREIGN KEY ("sectionId") REFERENCES "Section"("id") ON DELETE SET NULL ON UPDATE CASCADE;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "Homework" ADD CONSTRAINT "Homework_teacherId_fkey" FOREIGN KEY ("teacherId") REFERENCES "Teacher"("id") ON DELETE SET NULL ON UPDATE CASCADE;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "Homework" ADD CONSTRAINT "Homework_onlineClassId_fkey" FOREIGN KEY ("onlineClassId") REFERENCES "OnlineClass"("id") ON DELETE SET NULL ON UPDATE CASCADE;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "HomeworkAttachment" ADD CONSTRAINT "HomeworkAttachment_homeworkId_fkey" FOREIGN KEY ("homeworkId") REFERENCES "Homework"("id") ON DELETE CASCADE ON UPDATE CASCADE;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "HomeworkSubmission" ADD CONSTRAINT "HomeworkSubmission_homeworkId_fkey" FOREIGN KEY ("homeworkId") REFERENCES "Homework"("id") ON DELETE CASCADE ON UPDATE CASCADE;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "HomeworkSubmission" ADD CONSTRAINT "HomeworkSubmission_studentId_fkey" FOREIGN KEY ("studentId") REFERENCES "Student"("id") ON DELETE CASCADE ON UPDATE CASCADE;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "HomeworkSubmissionFile" ADD CONSTRAINT "HomeworkSubmissionFile_submissionId_fkey" FOREIGN KEY ("submissionId") REFERENCES "HomeworkSubmission"("id") ON DELETE CASCADE ON UPDATE CASCADE;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "OnlineClass" ADD CONSTRAINT "OnlineClass_schoolId_fkey" FOREIGN KEY ("schoolId") REFERENCES "School"("id") ON DELETE CASCADE ON UPDATE CASCADE;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "OnlineClass" ADD CONSTRAINT "OnlineClass_subjectId_fkey" FOREIGN KEY ("subjectId") REFERENCES "Subject"("id") ON DELETE SET NULL ON UPDATE CASCADE;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "OnlineClass" ADD CONSTRAINT "OnlineClass_teacherId_fkey" FOREIGN KEY ("teacherId") REFERENCES "Teacher"("id") ON DELETE SET NULL ON UPDATE CASCADE;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "OnlineClass" ADD CONSTRAINT "OnlineClass_classId_fkey" FOREIGN KEY ("classId") REFERENCES "Class"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "OnlineClass" ADD CONSTRAINT "OnlineClass_sectionId_fkey" FOREIGN KEY ("sectionId") REFERENCES "Section"("id") ON DELETE SET NULL ON UPDATE CASCADE;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "OnlineClassAttendance" ADD CONSTRAINT "OnlineClassAttendance_onlineClassId_fkey" FOREIGN KEY ("onlineClassId") REFERENCES "OnlineClass"("id") ON DELETE CASCADE ON UPDATE CASCADE;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "OnlineClassAttendance" ADD CONSTRAINT "OnlineClassAttendance_studentId_fkey" FOREIGN KEY ("studentId") REFERENCES "Student"("id") ON DELETE CASCADE ON UPDATE CASCADE;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "AcademicCalendarEvent" ADD CONSTRAINT "AcademicCalendarEvent_schoolId_fkey" FOREIGN KEY ("schoolId") REFERENCES "School"("id") ON DELETE CASCADE ON UPDATE CASCADE;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "AcademicCalendarEvent" ADD CONSTRAINT "AcademicCalendarEvent_classId_fkey" FOREIGN KEY ("classId") REFERENCES "Class"("id") ON DELETE SET NULL ON UPDATE CASCADE;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "AcademicCalendarEvent" ADD CONSTRAINT "AcademicCalendarEvent_sectionId_fkey" FOREIGN KEY ("sectionId") REFERENCES "Section"("id") ON DELETE SET NULL ON UPDATE CASCADE;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "AcademicCalendarEvent" ADD CONSTRAINT "AcademicCalendarEvent_teacherId_fkey" FOREIGN KEY ("teacherId") REFERENCES "Teacher"("id") ON DELETE SET NULL ON UPDATE CASCADE;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;
