/**
 * Opens a print window with styled HTML content.
 * Calls window.print() automatically.
 */
export function printHtml(htmlBody: string, title = "Document") {
  const win = window.open("", "_blank", "width=800,height=600");
  if (!win) {
    alert("Pop-up blocked. Please allow pop-ups for this site.");
    return;
  }
  win.document.write(`
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="utf-8" />
      <title>${title}</title>
      <style>
        * { box-sizing: border-box; margin: 0; padding: 0; }
        body { font-family: Arial, Helvetica, sans-serif; font-size: 13px; color: #111; padding: 24px; }
        h1 { font-size: 20px; font-weight: 700; }
        h2 { font-size: 16px; font-weight: 600; margin-bottom: 4px; }
        h3 { font-size: 14px; font-weight: 600; margin-bottom: 4px; }
        table { width: 100%; border-collapse: collapse; margin-top: 12px; }
        th, td { border: 1px solid #ddd; padding: 7px 10px; text-align: left; }
        th { background: #f5f5f5; font-weight: 600; font-size: 12px; }
        .header { display: flex; justify-content: space-between; align-items: flex-start; margin-bottom: 20px; padding-bottom: 16px; border-bottom: 2px solid #111; }
        .logo { font-size: 22px; font-weight: 800; color: #2563eb; }
        .meta { text-align: right; font-size: 12px; color: #555; }
        .section { margin-top: 20px; }
        .badge { display: inline-block; padding: 2px 8px; border-radius: 4px; font-size: 11px; font-weight: 600; }
        .paid { background: #d1fae5; color: #065f46; }
        .unpaid { background: #fee2e2; color: #991b1b; }
        .partial { background: #fef9c3; color: #78350f; }
        .footer { margin-top: 32px; text-align: center; font-size: 11px; color: #888; border-top: 1px solid #eee; padding-top: 12px; }
        @media print {
          body { padding: 0; }
          .no-print { display: none !important; }
        }
      </style>
    </head>
    <body>
      ${htmlBody}
      <div class="footer">Generated by Clever Campus ERP &bull; ${new Date().toLocaleString()}</div>
    </body>
    </html>`);
  win.document.close();
  setTimeout(() => { win.focus(); win.print(); }, 400);
}

/**
 * Generate a printable fee invoice HTML.
 */
export function buildFeeInvoiceHtml(opts: {
  schoolName: string;
  studentName: string;
  admissionNo: string;
  className?: string;
  sectionName?: string;
  invoiceNo: string;
  month: number;
  year: number;
  amount: number;
  discount?: number;
  fine?: number;
  totalAmount: number;
  paidAmount: number;
  status: string;
  dueDate?: string;
  payments?: { date: string; amount: number; method?: string }[];
}) {
  const MONTHS = ["January","February","March","April","May","June","July","August","September","October","November","December"];
  const balance = opts.totalAmount - opts.paidAmount;
  const statusClass = opts.status === "PAID" ? "paid" : opts.status === "PARTIAL" ? "partial" : "unpaid";
  const paymentsRows = (opts.payments ?? []).map(p => `
    <tr>
      <td>${new Date(p.date).toLocaleDateString()}</td>
      <td>PKR ${p.amount.toLocaleString()}</td>
      <td>${p.method ?? "—"}</td>
    </tr>`).join("");

  return `
    <div class="header">
      <div>
        <div class="logo">${opts.schoolName}</div>
        <div style="font-size:12px;color:#555;margin-top:2px">Fee Invoice</div>
      </div>
      <div class="meta">
        <div><strong>Invoice No:</strong> ${opts.invoiceNo}</div>
        <div><strong>Month:</strong> ${MONTHS[opts.month - 1]} ${opts.year}</div>
        <div><strong>Status:</strong> <span class="badge ${statusClass}">${opts.status}</span></div>
        ${opts.dueDate ? `<div><strong>Due Date:</strong> ${new Date(opts.dueDate).toLocaleDateString()}</div>` : ""}
      </div>
    </div>

    <div class="section">
      <h3>Student Information</h3>
      <table>
        <tr><th>Name</th><td>${opts.studentName}</td><th>Admission No</th><td>${opts.admissionNo}</td></tr>
        <tr><th>Class</th><td>${opts.className ?? "—"}</td><th>Section</th><td>${opts.sectionName ?? "—"}</td></tr>
      </table>
    </div>

    <div class="section">
      <h3>Fee Details</h3>
      <table>
        <tr><th>Description</th><th>Amount (PKR)</th></tr>
        <tr><td>Monthly Fee</td><td>${opts.amount.toLocaleString()}</td></tr>
        ${opts.discount ? `<tr><td>Discount</td><td style="color:#16a34a">- ${opts.discount.toLocaleString()}</td></tr>` : ""}
        ${opts.fine ? `<tr><td>Fine / Late Charges</td><td style="color:#dc2626">+ ${opts.fine.toLocaleString()}</td></tr>` : ""}
        <tr style="font-weight:700"><td>Total Amount</td><td>PKR ${opts.totalAmount.toLocaleString()}</td></tr>
        <tr><td>Amount Paid</td><td style="color:#16a34a">PKR ${opts.paidAmount.toLocaleString()}</td></tr>
        <tr style="font-weight:700"><td>Balance Due</td><td style="color:${balance > 0 ? "#dc2626" : "#16a34a"}">PKR ${balance.toLocaleString()}</td></tr>
      </table>
    </div>

    ${paymentsRows ? `
    <div class="section">
      <h3>Payment History</h3>
      <table>
        <thead><tr><th>Date</th><th>Amount</th><th>Method</th></tr></thead>
        <tbody>${paymentsRows}</tbody>
      </table>
    </div>` : ""}
  `;
}

/**
 * Generate a salary slip HTML.
 */
export function buildSalarySlipHtml(opts: {
  schoolName: string;
  employeeName: string;
  employeeType: string;
  designation?: string;
  month: number;
  year: number;
  basicSalary: number;
  allowances?: number;
  deductions?: number;
  netSalary: number;
  status: string;
  paidOn?: string;
}) {
  const MONTHS = ["January","February","March","April","May","June","July","August","September","October","November","December"];
  return `
    <div class="header">
      <div>
        <div class="logo">${opts.schoolName}</div>
        <div style="font-size:12px;color:#555;margin-top:2px">Salary Slip</div>
      </div>
      <div class="meta">
        <div><strong>Month:</strong> ${MONTHS[opts.month - 1]} ${opts.year}</div>
        <div><strong>Status:</strong> <span class="badge ${opts.status === "PAID" ? "paid" : "unpaid"}">${opts.status}</span></div>
        ${opts.paidOn ? `<div><strong>Paid On:</strong> ${new Date(opts.paidOn).toLocaleDateString()}</div>` : ""}
      </div>
    </div>

    <div class="section">
      <h3>Employee Information</h3>
      <table>
        <tr><th>Name</th><td>${opts.employeeName}</td><th>Type</th><td>${opts.employeeType}</td></tr>
        ${opts.designation ? `<tr><th>Designation</th><td colspan="3">${opts.designation}</td></tr>` : ""}
      </table>
    </div>

    <div class="section">
      <h3>Earnings & Deductions</h3>
      <table>
        <tr><th>Description</th><th>Amount (PKR)</th></tr>
        <tr><td>Basic Salary</td><td>${opts.basicSalary.toLocaleString()}</td></tr>
        ${opts.allowances ? `<tr><td>Allowances</td><td style="color:#16a34a">+ ${opts.allowances.toLocaleString()}</td></tr>` : ""}
        ${opts.deductions ? `<tr><td>Deductions</td><td style="color:#dc2626">- ${opts.deductions.toLocaleString()}</td></tr>` : ""}
        <tr style="font-weight:700;background:#f5f5f5"><td>Net Salary</td><td>PKR ${opts.netSalary.toLocaleString()}</td></tr>
      </table>
    </div>
  `;
}

/**
 * Trigger a CSV file download from arrays of data.
 */
export function downloadCSV(filename: string, headers: string[], rows: (string | number | null | undefined)[][]) {
  const escape = (v: string | number | null | undefined) => {
    const s = String(v ?? "");
    return s.includes(",") || s.includes('"') || s.includes("\n")
      ? `"${s.replace(/"/g, '""')}"`
      : s;
  };
  const csvContent = [headers, ...rows].map(row => row.map(escape).join(",")).join("\n");
  const blob = new Blob([csvContent], { type: "text/csv;charset=utf-8;" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}
